using System.Collections.Generic;
using System.Text;

using Cursorial.UI.Xaml; // frontend node graph (internals via InternalsVisibleTo)
using Microsoft.CodeAnalysis;

namespace Cursorial.UI.Xaml.Generator;

/// <summary>
/// WS-X4.6 — the code-behind half of the generated partial: typed <c>x:Name</c> fields +
/// <c>InitializeComponent()</c>. Given a symbol-backed parse (so <c>ResolvedTypes</c> carry
/// <see cref="RoslynXamlType"/> identities), it collects the document-scope named elements and their
/// resolved types and emits a <c>partial class</c> matching the <c>x:Class</c> directive.
/// </summary>
/// <remarks>
/// v1 authoring model (design doc P10 / plan): <c>InitializeComponent</c> calls the runtime loader
/// (<c>XamlLoader.Shared.LoadComponent(this, doc)</c>) over a once-parsed cached <see cref="XamlDocument"/>,
/// then assigns each typed field from the document name scope — no object-construction codegen (that's X5).
/// The cached document parses at runtime through the AOT-clean generated provider (installed by the
/// generated module initializer), so the published app stays reflection-free. Names inside resource
/// dictionaries (no name scope) and deferred/template content (a separate template scope) are NOT fields.
/// </remarks>
internal static class CodeBehindEmitter
{
    /// <summary>A document-scope named element: its <c>x:Name</c> and resolved element type.</summary>
    internal readonly record struct NamedElement(string Name, INamedTypeSymbol Type);

    /// <summary>Collects the <c>x:Class</c> name + the document-scope (name → type) pairs from a parsed document.</summary>
    public static (string? RootClass, IReadOnlyList<NamedElement> Named) Collect(XamlDocument document)
    {
        var named = new List<NamedElement>();
        var seen = new HashSet<string>(System.StringComparer.Ordinal);

        var objects = document.Objects;
        var members = document.Members;
        var strings = document.Strings;
        var resolvedTypes = document.ResolvedTypes;

        for (int i = 0; i < objects.Length; i++)
        {
            ref readonly var obj = ref objects[i];

            if (!obj.HasFlag(ObjectFlags.HasName))
                continue;

            // x:Name inside a resource dictionary has no name scope (X104); inside deferred/template content
            // it lives in a per-instantiation template scope — neither becomes a code-behind field.
            if (obj.HasFlag(ObjectFlags.InResourceDictionary) || obj.HasFlag(ObjectFlags.InDeferredContent))
                continue;

            string? name = null;

            for (int m = obj.MemberStart; m < obj.MemberStart + obj.MemberCount; m++)
            {
                ref readonly var member = ref members[m];

                if (member.Kind == XamlValueKind.Directive && member.DirectiveKind == (int) XamlDirectiveKind.Name)
                {
                    name = strings[member.ValueIndex];
                    break;
                }
            }

            if (name is null || !seen.Add(name)) // dedup: a duplicate name is the parser's diagnostic, not a CS0102
                continue;

            // The element's resolved type identity is a RoslynXamlType (symbol-backed parse). Skip if the type
            // did not resolve (can't emit a typed field) — the parser already reported the resolution failure.
            if (obj.TypeId >= 0 && resolvedTypes[obj.TypeId]?.ClrType is RoslynXamlType { Symbol: INamedTypeSymbol symbol })
                named.Add(new NamedElement(name, symbol));
        }

        return (document.RootClassName, named);
    }

    /// <summary>
    /// Emits the code-behind partial for an <c>x:Class</c> document, or <see langword="null"/> when there is
    /// no <c>x:Class</c> (a class-less document has no code-behind to extend).
    /// </summary>
    public static string? Emit(XamlDocument document, string xamlText, string xamlPath)
    {
        var (rootClass, named) = Collect(document);

        if (rootClass is not { Length: > 0 })
            return null;

        int dot = rootClass.LastIndexOf('.');
        string? ns = dot > 0 ? rootClass.Substring(0, dot) : null;
        string className = dot > 0 ? rootClass.Substring(dot + 1) : rootClass;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Cursorial.UI.Xaml.Generator — code-behind (WS-X4.6)");
        sb.AppendLine($"// source: {xamlPath}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        string indent = ns is null ? string.Empty : "    ";

        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"{indent}partial class {className}");
        sb.AppendLine($"{indent}{{");

        // Typed x:Name fields. `null!` (the value is always assigned by InitializeComponent before any read).
        foreach (var ne in named)
            sb.AppendLine($"{indent}    internal {Global(ne.Type)} {ne.Name} = null!;");

        if (named.Count > 0)
            sb.AppendLine();

        // The XAML is parsed ONCE into an immutable, shareable document (cached static) and instantiated per
        // InitializeComponent call via the runtime loader, populating `this` as the root.
        sb.AppendLine($"{indent}    private const string __XamlSource = {Verbatim(xamlText)};");
        sb.AppendLine();
        sb.AppendLine($"{indent}    private static readonly global::Cursorial.UI.Xaml.XamlDocument __XamlDocument =");

        sb.AppendLine($"{indent}        global::Cursorial.UI.Xaml.XamlLoader.Shared.Parse(__XamlSource, " +
                      $"new global::System.Uri({Verbatim(xamlPath)}, global::System.UriKind.RelativeOrAbsolute));");

        sb.AppendLine();
        sb.AppendLine($"{indent}    private bool __contentLoaded;");
        sb.AppendLine();
        sb.AppendLine($"{indent}    internal void InitializeComponent()");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        if (__contentLoaded) return;");
        sb.AppendLine($"{indent}        __contentLoaded = true;");
        sb.AppendLine($"{indent}        global::Cursorial.UI.Xaml.XamlLoader.Shared.LoadComponent(this, __XamlDocument);");

        if (named.Count > 0)
        {
            sb.AppendLine($"{indent}        var __scope = global::Cursorial.UI.NameScope.GetNameScope(this);");

            foreach (var ne in named)
                sb.AppendLine($"{indent}        this.{ne.Name} = ({Global(ne.Type)})__scope!.Find(\"{ne.Name}\")!;");
        }

        sb.AppendLine($"{indent}    }}");

        sb.AppendLine($"{indent}}}");

        if (ns is not null)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private static string Global(ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    // A C# verbatim string literal (@"...") with embedded double-quotes doubled. Backslashes are literal.
    private static string Verbatim(string text) => "@\"" + text.Replace("\"", "\"\"") + "\"";
}