using System.Collections.Generic;
using System.Linq;
using System.Text;

using Cursorial.UI.Xaml; // frontend node graph (internals via InternalsVisibleTo)

using Microsoft.CodeAnalysis;

namespace Cursorial.UI.Xaml.Generator;

/// <summary>
/// WS-X5 — the full-lowering code-behind generator. Where <see cref="CodeBehindEmitter"/> (X4 v1) emits an
/// <c>InitializeComponent</c> that calls the runtime loader, this emits the object graph as straight-line
/// C# — element construction, property/collection assignment, x:Name fields — so there is NO runtime parse
/// or reflection (the reflection-free / zero-AOT-warning route). Driven by the symbol-backed parse
/// (<see cref="RoslynXamlMetadata"/>) so resolved types/members carry their Roslyn symbols.
/// </summary>
/// <remarks>
/// SPINE scope (this workstream): element construction, registered-<c>UIProperty</c> <c>SetValue</c> and CLR
/// property sets for <c>object</c>/<c>string</c> values, content-property single + collection assignment, and
/// typed <c>x:Name</c> fields + name scope. Value conversion (typed literals), attached properties, events,
/// markup extensions, templates, and resources are later X5 workstreams — a member this spine can't yet
/// lower is emitted as a <c>// TODO X5</c> marker rather than wrong code.
/// </remarks>
internal static class LoweringEmitter
{
    public static LoweringResult? Emit(XamlDocument document, string xamlPath, XamlSymbolResolver resolver)
    {
        if (!document.HasObjects)
            return null;

        var (rootClass, named) = CodeBehindEmitter.Collect(document);
        if (rootClass is not { Length: > 0 })
            return null;

        int dot = rootClass.LastIndexOf('.');
        string? ns = dot > 0 ? rootClass.Substring(0, dot) : null;
        string className = dot > 0 ? rootClass.Substring(dot + 1) : rootClass;
        string indent = ns is null ? "    " : "        ";

        var ctx = new Context(document, indent, resolver);

        // Build the InitializeComponent body first (it determines whether a name scope is needed).
        if (named.Count > 0)
        {
            ctx.Line("var __scope = new global::Cursorial.UI.NameScopeDictionary();");
            ctx.Line("global::Cursorial.UI.NameScope.SetNameScope(this, __scope);");
        }
        EmitObject(ctx, objectIndex: 0, varExpr: "this", isRoot: true, hasScope: named.Count > 0, dataType: null);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Cursorial.UI.Xaml.Generator — full-lowering code-behind (WS-X5)");
        sb.AppendLine($"// source: {xamlPath}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        string ci = ns is null ? string.Empty : "    ";
        sb.AppendLine($"{ci}partial class {className}");
        sb.AppendLine($"{ci}{{");
        foreach (var ne in named)
            sb.AppendLine($"{ci}    internal {Global(ne.Type)} {ne.Name} = null!;");
        if (named.Count > 0)
            sb.AppendLine();
        sb.AppendLine($"{ci}    private bool __contentLoaded;");
        sb.AppendLine();
        sb.AppendLine($"{ci}    internal void InitializeComponent()");
        sb.AppendLine($"{ci}    {{");
        sb.AppendLine($"{ci}        if (__contentLoaded) return;");
        sb.AppendLine($"{ci}        __contentLoaded = true;");
        sb.Append(ctx.Body);
        sb.AppendLine($"{ci}    }}");

        if (ctx.UsesConverter)
        {
            // The (hand-written, AOT-clean) converter ladder for typed literals. No reflection except the
            // named-color/TypeDescriptor edges in the ladder itself (tracked for later AOT-hardening).
            sb.AppendLine();
            sb.AppendLine($"{ci}    private static object? __ConvertXamlValue(global::System.Type targetType, string text)");
            sb.AppendLine($"{ci}        => global::Cursorial.UI.Xaml.XamlConverters.For(targetType) is {{ }} __c");
            sb.AppendLine($"{ci}            ? __c.ConvertFromString(text, new global::Cursorial.UI.Xaml.XamlValueContext(");
            sb.AppendLine($"{ci}                global::System.Globalization.CultureInfo.InvariantCulture, null, targetType, null, 0, 0))");
            sb.AppendLine($"{ci}            : text;");
        }

        sb.AppendLine($"{ci}}}");
        if (ns is not null)
            sb.AppendLine("}");

        return new LoweringResult(sb.ToString(), ctx.Unlowered);
    }

    private static void EmitObject(Context c, int objectIndex, string varExpr, bool isRoot, bool hasScope, INamedTypeSymbol? dataType)
    {
        ref readonly var obj = ref c.Doc.Objects[objectIndex];
        c.CurrentLineInfo = obj.PackedLineInfo;

        if (!isRoot)
        {
            var typeSymbol = TypeSymbolOf(c.Doc, obj.TypeId);
            if (typeSymbol is null)
            {
                c.Todo($"unresolved element type (object {objectIndex})");
                return;
            }
            c.Line($"var {varExpr} = new {Global(typeSymbol)}();");
        }

        // An x:DataType on this object establishes the compiled-binding source type for its whole subtree
        // (B184/B3); otherwise the enclosing scope's type carries down.
        dataType = XamlDataTypeScope.ForObject(c.Doc, in obj, c.Resolver) ?? dataType;

        for (int m = obj.MemberStart; m < obj.MemberStart + obj.MemberCount; m++)
        {
            ref readonly var member = ref c.Doc.Members[m];
            c.CurrentLineInfo = member.PackedLineInfo;

            if (member.Kind == XamlValueKind.Directive)
            {
                if (member.DirectiveKind == (int)XamlDirectiveKind.Name && hasScope)
                {
                    var name = c.Doc.Strings[member.ValueIndex];
                    c.Line($"this.{name} = {varExpr};");
                    c.Line($"__scope.Register(\"{name}\", {varExpr});");
                }
                continue; // x:Class/x:Key/x:DataType: no lowered effect here
            }

            var xm = member.MemberId >= 0 ? c.Doc.ResolvedMembers[member.MemberId] : null;
            if (xm is null)
                continue;

            switch (member.Kind)
            {
                case XamlValueKind.Text:
                    EmitScalarAssign(c, varExpr, xm, c.Doc.Strings[member.ValueIndex]);
                    break;

                case XamlValueKind.Object:
                {
                    var childVar = c.NextVar();
                    EmitObject(c, member.ValueIndex, childVar, isRoot: false, hasScope, dataType);
                    EmitChildAssign(c, varExpr, xm, childVar, single: true);
                    break;
                }

                case XamlValueKind.Items:
                {
                    int childIndex = member.ValueIndex;
                    for (int i = 0; i < member.ItemCount; i++)
                    {
                        var childVar = c.NextVar();
                        EmitObject(c, childIndex, childVar, isRoot: false, hasScope, dataType);
                        EmitChildAssign(c, varExpr, xm, childVar, single: false);
                        childIndex += c.Doc.Objects[childIndex].SubtreeLength; // depth-first contiguous
                    }
                    break;
                }

                case XamlValueKind.Extension:
                    EmitExtensionAssign(c, varExpr, xm, in c.Doc.Extensions[member.ValueIndex], dataType);
                    break;

                case XamlValueKind.Event:
                    // Click="OnClick" → `__e.Click += this.OnClick;`. The handler is resolved at the consumer's
                    // compile (a missing/mismatched handler is a CS error). The runtime loader no-ops events at
                    // X1, so lowering is strictly more capable here.
                    c.Line($"{varExpr}.{xm.Name} += this.{c.Doc.Strings[member.ValueIndex]};");
                    break;

                case XamlValueKind.Folded:
                    // Under FoldConstants=false the only Folded members are the intrinsic extensions:
                    // {x:Null} (a null constant) and {x:Static} (a XamlStaticReference carrying the member path).
                    EmitFoldedAssign(c, varExpr, xm, c.Doc.Constants[member.ValueIndex]);
                    break;

                default:
                    c.Todo($"member '{xm.Name}' kind {member.Kind} not yet lowered");
                    break;
            }
        }
    }

    // A Text value: an object/string member takes the string literal directly; any other typed member runs
    // the (hand-written, AOT-clean) converter ladder via the emitted __ConvertXamlValue helper (X5.1).
    private static void EmitScalarAssign(Context c, string varExpr, XamlMember xm, string text)
    {
        string valueExpr;
        if (IsObjectOrString(xm.ValueType))
        {
            valueExpr = $"\"{Escape(text)}\"";
        }
        else if (ValueTypeSymbol(xm.ValueType) is { } valueType)
        {
            c.UsesConverter = true;
            valueExpr = $"__ConvertXamlValue(typeof({Global(valueType)}), \"{Escape(text)}\")";
        }
        else
        {
            c.Todo($"unresolved value type for {xm.Name}=\"{Escape(text)}\"");
            return;
        }

        if (RegisteredOwner(xm) is { } owner)
            // SetValue takes object? — no cast needed.
            c.Line($"{varExpr}.SetValue({Global(owner)}.{xm.Name}Property, {valueExpr});");
        else if (IsObjectOrString(xm.ValueType))
            c.Line($"{varExpr}.{xm.Name} = {valueExpr};");
        else
            // CLR setter wants the property type — cast the converter's object? result.
            c.Line($"{varExpr}.{xm.Name} = ({Global(ValueTypeSymbol(xm.ValueType)!)}){valueExpr}!;");
    }

    // A child element value: a registered-collection content member fills via Add; a single member is set
    // (SetValue for a UIProperty, else the CLR setter).
    private static void EmitChildAssign(Context c, string varExpr, XamlMember xm, string childVar, bool single)
    {
        if (!single)
        {
            c.Line($"{varExpr}.{xm.Name}.Add({childVar});");
            return;
        }

        if (RegisteredOwner(xm) is { } owner)
            c.Line($"{varExpr}.SetValue({Global(owner)}.{xm.Name}Property, {childVar});");
        else
            c.Line($"{varExpr}.{xm.Name} = {childVar};");
    }

    // {x:Null} → null; {x:Static Type.Member} → the resolved static reference (global::Type.Member).
    private static void EmitFoldedAssign(Context c, string varExpr, XamlMember xm, object? constant)
    {
        string? valueExpr = constant switch
        {
            null => "null",
            XamlStaticReference staticRef => ResolveStaticPath(c, staticRef.MemberPath),
            _ => null, // not expected under FoldConstants=false
        };

        if (valueExpr is null)
        {
            c.Todo($"folded value for {xm.Name} ({constant?.GetType().Name ?? "null"})");
            return;
        }

        if (RegisteredOwner(xm) is { } owner)
            c.Line($"{varExpr}.SetValue({Global(owner)}.{xm.Name}Property, {valueExpr});");
        else
            c.Line($"{varExpr}.{xm.Name} = {valueExpr};");
    }

    // ── {Binding} (B3a — the compiled lane) ──────────────────────────────────────────────────────

    private static void EmitExtensionAssign(Context c, string varExpr, XamlMember xm, in ExtensionRecord ext, INamedTypeSymbol? dataType)
    {
        switch (ext.Kind)
        {
            case ExtensionKind.Binding when c.Doc.ParsedExtensions[ext.Payload] is { } node:
                EmitBinding(c, varExpr, xm, node, dataType);
                return;

            case ExtensionKind.DynamicResource:
                EmitDynamicResource(c, varExpr, xm, in ext);
                return;

            // StaticResource (eager) and TemplateBinding lowering are later X5.4 sub-workstreams.
            default:
                c.Todo($"extension {ext.Kind} for '{xm.Name}' not yet lowered");
                return;
        }
    }

    // {DynamicResource Key} → ResourceExtensions.SetResourceReference(element, Owner.FooProperty, key): a live
    // producer that re-resolves against the element's ancestor chain on attach (no eager-resolution timing
    // problem — works inline AND inside templates). Requires a registered StyledProperty<T> target (the runtime
    // handler rejects direct/attached); a literal key only (a nested-extension key is deferred to a later cut).
    private static void EmitDynamicResource(Context c, string varExpr, XamlMember xm, in ExtensionRecord ext)
    {
        if (ext.PayloadIsParsedExtension)
        {
            c.Todo($"{{DynamicResource}} with a markup-extension key for '{xm.Name}' not yet lowered");
            return;
        }

        if (RegisteredOwner(xm) is not { } owner || !XamlDataTypeScope.IsStyledProperty(owner, xm.Name))
        {
            c.Todo($"{{DynamicResource}} target '{xm.Name}' is not a styled UIProperty (direct/attached unsupported)");
            return;
        }

        var key = c.Doc.Strings[ext.Payload];
        // SetResourceReference<T> infers T from the StyledProperty<T> field; call it statically (no using).
        c.Line($"global::Cursorial.UI.ResourceExtensions.SetResourceReference({varExpr}, {Global(owner)}.{xm.Name}Property, \"{Escape(key)}\");");
    }

    // B3a/B3b — {Binding} lowering. The compiled lane (zero reflection, AOT-clean) is taken for an
    // x:DataType-scoped, DataContext-relative, single-hop binding; everything else falls back to a faithful
    // reflective `new Binding(...)` (the plan's "graceful reflective fallback" — the binding still works, just
    // through the reflective engine, which surfaces an AOT warning pointing at the binding to fix). Only a
    // Converter-bearing binding (needs eager resource/static resolution, deferred with resources) or an
    // unsupported RelativeSource stays a // TODO X5.
    private static void EmitBinding(Context c, string varExpr, XamlMember xm, MarkupExtensionNode node, INamedTypeSymbol? dataType)
    {
        // A binding target must be a registered UIProperty — the runtime handler enforces the same (X119).
        if (RegisteredOwner(xm) is not { } owner)
        {
            c.Todo($"binding target '{xm.Name}' is not a bindable UIProperty");
            return;
        }

        if (TryEmitCompiledBinding(c, varExpr, owner, xm, node, dataType))
            return;

        EmitReflectiveBinding(c, varExpr, owner, xm, node);
    }

    private static bool TryEmitCompiledBinding(
        Context c, string varExpr, INamedTypeSymbol owner, XamlMember xm, MarkupExtensionNode node, INamedTypeSymbol? dataType)
    {
        if (dataType is null)
            return false;

        // Only a plain DataContext-relative binding is x:DataType-rooted; any anchor/converter/format/fallback
        // arg changes semantics this lane doesn't yet reproduce — bail so it isn't silently dropped.
        if (HasNamed(node, "Source") || HasNamed(node, "ElementName") || HasNamed(node, "RelativeSource") ||
            HasNamed(node, "Converter") || HasNamed(node, "StringFormat") || HasNamed(node, "FallbackValue"))
        {
            return false;
        }

        var path = BindingPathOf(node);
        if (string.IsNullOrEmpty(path) || path == ".")
            return false;

        // Single-hop only in B3a (multi-hop getter/steps + null-propagation is a later workstream).
        if (path!.IndexOf('.') >= 0 || path.IndexOf('[') >= 0 || path.IndexOf('(') >= 0)
            return false;

        if (CanonicalMode(node) is not { } modeName) // an unknown Mode token — bail to the reflective fallback
            return false;

        if (XamlDataTypeScope.FindMember(dataType, path) is not { IsStatic: false } leaf ||
            XamlDataTypeScope.MemberType(leaf) is not { } leafType ||
            !XamlDataTypeScope.IsReadable(leaf))
        {
            // A static-named path can't be `__s.Member` (CS0176) — bail to the reflective fallback (which
            // resolves instance-or-static identically to the runtime loader's reflective binding).
            return false;
        }

        string data = Global(dataType);
        string value = Global(leafType);
        string getter = $"static __s => __s.{path}";
        // A writable leaf gets a reverse setter (TwoWay/Default-on-a-two-way-property work); a read-only leaf
        // passes null (the engine degrades a TwoWay use to OneWay — B152), mirroring the reflective lane.
        string setter = XamlDataTypeScope.IsWritable(leaf) ? $"static (__s, __v) => __s.{path} = __v" : "null";
        string step = $"new global::Cursorial.UI.Data.CompiledPathStep(\"{Escape(path)}\", static __o => (object?)(({data}) __o!).{path})";

        c.Line(
            $"global::Cursorial.UI.Data.BindingOperations.Install({varExpr}, {Global(owner)}.{xm.Name}Property, " +
            $"new global::Cursorial.UI.Data.CompiledBinding<{data}, {value}>({getter}, {setter}, " +
            $"new global::Cursorial.UI.Data.CompiledPathStep[] {{ {step} }}, \"{Escape(path)}\"){Initializers(ModeInit(modeName))});");
        return true;
    }

    // The reflective fallback (B3b) — a faithful `new Binding(path) { … }` mirroring the runtime handler's
    // BuildBinding (Mode/ElementName/Source/StringFormat/FallbackValue/RelativeSource), minus Converter.
    private static void EmitReflectiveBinding(Context c, string varExpr, INamedTypeSymbol owner, XamlMember xm, MarkupExtensionNode node)
    {
        // A Converter needs eager resource/static resolution, which lowering doesn't do yet — defer (X5.4).
        if (HasNamed(node, "Converter"))
        {
            c.Todo($"{{Binding}} with a Converter for '{xm.Name}' not yet lowered (needs resource lowering)");
            return;
        }

        if (CanonicalMode(node) is not { } modeName)
        {
            c.Todo($"{{Binding}} with an unrecognized Mode for '{xm.Name}'");
            return;
        }

        if (RelativeSourceInit(node) is not { } relSource)
        {
            c.Todo($"{{Binding}} RelativeSource for '{xm.Name}' not supported in lowering (Self/TemplatedParent only)");
            return;
        }

        string path = Escape(BindingPathOf(node) ?? string.Empty);
        var inits = new List<string>(ModeInit(modeName))
        {
            relSource,
            StringInit("ElementName", NamedText(node, "ElementName")),
            StringInit("Source", NamedText(node, "Source")),       // mirrors the handler: Source = the bare string
            StringInit("StringFormat", NamedText(node, "StringFormat")),
            StringInit("FallbackValue", NamedText(node, "FallbackValue")),
        };

        c.Line(
            $"global::Cursorial.UI.Data.BindingOperations.Install({varExpr}, {Global(owner)}.{xm.Name}Property, " +
            $"new global::Cursorial.UI.Data.Binding(\"{path}\"){Initializers(inits)});");
    }

    // The binding path: the first positional argument, else the Path= named argument (mirrors the runtime handler).
    private static string? BindingPathOf(MarkupExtensionNode node)
        => node.PositionalArguments.Count > 0 && node.PositionalArguments[0].Text is { } p ? p : NamedText(node, "Path");

    private static bool HasNamed(MarkupExtensionNode node, string name) => node.FindNamed(name) is not null;

    private static string? NamedText(MarkupExtensionNode node, string name)
        => node.FindNamed(name) is { Text: { } t } ? t : null;

    private static string? FirstPositionalText(MarkupExtensionNode node)
        => node.PositionalArguments.Count > 0 ? node.PositionalArguments[0].Text : null;

    // The canonical BindingMode member name; "" for unspecified (Default — resolved at install, BD10); null for
    // an unrecognized token (the caller bails — the compiled path to the reflective fallback, the fallback to TODO).
    private static string? CanonicalMode(MarkupExtensionNode node)
    {
        if (NamedText(node, "Mode") is not { } text)
            return string.Empty;

        // BindingMode is a closed enum; match case-insensitively (WPF/Avalonia parity with the runtime handler).
        return text.ToLowerInvariant() switch
        {
            "default" => "Default",
            "oneway" => "OneWay",
            "twoway" => "TwoWay",
            "onetime" => "OneTime",
            "onewaytosource" => "OneWayToSource",
            _ => null,
        };
    }

    // The `Mode = BindingMode.X` initializer fragment for a carried mode ("" when unspecified ⇒ no fragment).
    private static IEnumerable<string> ModeInit(string modeName)
        => modeName.Length == 0 ? [] : [$"Mode = global::Cursorial.UI.Data.BindingMode.{modeName}"];

    private static string StringInit(string member, string? value)
        => value is null ? string.Empty : $"{member} = \"{Escape(value)}\"";

    // The `RelativeSource = …` fragment: "" not present; the Self/TemplatedParent fragment; null for an
    // unsupported mode (FindAncestor etc. — the caller TODOs), mirroring the handler's ParseRelativeSource.
    private static string? RelativeSourceInit(MarkupExtensionNode node)
    {
        if (node.FindNamed("RelativeSource") is not { } value)
            return string.Empty;

        string? mode = value.IsNested
            ? FirstPositionalText(value.Nested!) ?? NamedText(value.Nested!, "Mode")
            : value.Text;

        return mode switch
        {
            "TemplatedParent" => "RelativeSource = global::Cursorial.UI.Data.RelativeSource.TemplatedParent",
            "Self" => "RelativeSource = global::Cursorial.UI.Data.RelativeSource.Self",
            null when value.IsNested => "RelativeSource = global::Cursorial.UI.Data.RelativeSource.Self", // WPF default
            _ => null,
        };
    }

    // Joins non-empty object-initializer member assignments into a ` { a, b }` suffix, or "" when none.
    private static string Initializers(IEnumerable<string> members)
    {
        var present = members.Where(s => s.Length > 0).ToList();
        return present.Count == 0 ? string.Empty : " { " + string.Join(", ", present) + " }";
    }

    // Resolves an {x:Static Type.Member} path to a C# static reference. The type token (before the last dot)
    // is resolved through the same symbol resolver the parse used (default UI xmlns); the member is appended.
    private static string? ResolveStaticPath(Context c, string memberPath)
    {
        int dot = memberPath.LastIndexOf('.');
        if (dot <= 0)
            return null;

        var typeName = memberPath.Substring(0, dot);
        var member = memberPath.Substring(dot + 1);
        var typeSymbol = c.Resolver.Resolve(XamlSymbolResolver.CursorialUiNamespace, typeName, out _);
        return typeSymbol is null ? null : $"{Global(typeSymbol)}.{member}"; // Global() already prefixes global::
    }

    private static INamedTypeSymbol? RegisteredOwner(XamlMember member) => member.Property as INamedTypeSymbol;

    private static bool IsObjectOrString(IXamlType valueType)
        => valueType is RoslynXamlType { Symbol.SpecialType: SpecialType.System_Object or SpecialType.System_String };

    private static ITypeSymbol? ValueTypeSymbol(IXamlType valueType)
        => valueType is RoslynXamlType { Symbol: { } symbol } ? symbol : null;

    private static INamedTypeSymbol? TypeSymbolOf(XamlDocument document, int typeId)
        => typeId >= 0 && document.ResolvedTypes[typeId]?.ClrType is RoslynXamlType { Symbol: INamedTypeSymbol s } ? s : null;

    private static string Global(ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string Escape(string text) => text.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed class Context(XamlDocument document, string indent, XamlSymbolResolver resolver)
    {
        public XamlDocument Doc { get; } = document;
        public XamlSymbolResolver Resolver { get; } = resolver;
        public StringBuilder Body { get; } = new();
        public bool UsesConverter { get; set; }
        public List<UnloweredMember> Unlowered { get; } = [];

        /// <summary>The packed source position of the member currently being lowered — stamps any TODO note.</summary>
        public int CurrentLineInfo { get; set; }

        private int _counter;

        public string NextVar() => $"__e{_counter++}";

        public void Line(string statement) => Body.AppendLine(indent + statement);

        /// <summary>
        /// Records a feature the full-lowering can't yet emit: leaves a visible <c>// TODO X5</c> marker in the
        /// generated code AND a note the generator surfaces as a build warning (so an opted-in <c>full</c> build
        /// never silently drops a member — the marker alone would be invisible at the call site).
        /// </summary>
        public void Todo(string message)
        {
            Line("// TODO X5: " + message);
            Unlowered.Add(new UnloweredMember(message, LineInfo.Line(CurrentLineInfo), LineInfo.Column(CurrentLineInfo)));
        }
    }

    /// <summary>The lowered source plus the members it couldn't emit (each a build-warning candidate).</summary>
    public readonly struct LoweringResult(string source, IReadOnlyList<UnloweredMember> unlowered)
    {
        public string Source { get; } = source;
        public IReadOnlyList<UnloweredMember> Unlowered { get; } = unlowered;
    }

    /// <summary>A member the full-lowering couldn't emit, with its 1-based source position (0 if unknown).</summary>
    public readonly struct UnloweredMember(string message, int line, int column)
    {
        public string Message { get; } = message;
        public int Line { get; } = line;
        public int Column { get; } = column;
    }
}
