using System.Collections.Generic;
using System.Text;

using Cursorial.UI.Xaml; // frontend node graph (internals via InternalsVisibleTo)

using Microsoft.CodeAnalysis;

namespace Cursorial.UI.Xaml.Generator;

/// <summary>
/// WS-X5 — the full-lowering code-behind generator. Where <see cref="CodeBehindEmitter"/> (X4 v1) emits an
/// <c>InitializeComponent</c> that calls the runtime loader, this emits the object graph as straight-line
/// C# — element construction, property/collection assignment, x:Name fields — so there is NO runtime parse
/// or reflection (the reflection-free / zero-AOT-warning route). Driven by the symbol-backed parse
/// (<see cref="RoslynXamlMetadata"/>) so resolved types/members carry their Roslyn symbols.
/// </summary>
/// <remarks>
/// SPINE scope (this workstream): element construction, registered-<c>UIProperty</c> <c>SetValue</c> and CLR
/// property sets for <c>object</c>/<c>string</c> values, content-property single + collection assignment, and
/// typed <c>x:Name</c> fields + name scope. Value conversion (typed literals), attached properties, events,
/// markup extensions, templates, and resources are later X5 workstreams — a member this spine can't yet
/// lower is emitted as a <c>// TODO X5</c> marker rather than wrong code.
/// </remarks>
internal static class LoweringEmitter
{
    public static string? Emit(XamlDocument document, string xamlPath)
    {
        if (!document.HasObjects)
            return null;

        var (rootClass, named) = CodeBehindEmitter.Collect(document);
        if (rootClass is not { Length: > 0 })
            return null;

        int dot = rootClass.LastIndexOf('.');
        string? ns = dot > 0 ? rootClass.Substring(0, dot) : null;
        string className = dot > 0 ? rootClass.Substring(dot + 1) : rootClass;
        string indent = ns is null ? "    " : "        ";

        var ctx = new Context(document, indent);

        // Build the InitializeComponent body first (it determines whether a name scope is needed).
        if (named.Count > 0)
        {
            ctx.Line("var __scope = new global::Cursorial.UI.NameScopeDictionary();");
            ctx.Line("global::Cursorial.UI.NameScope.SetNameScope(this, __scope);");
        }
        EmitObject(ctx, objectIndex: 0, varExpr: "this", isRoot: true, hasScope: named.Count > 0);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Cursorial.UI.Xaml.Generator — full-lowering code-behind (WS-X5)");
        sb.AppendLine($"// source: {xamlPath}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        string ci = ns is null ? string.Empty : "    ";
        sb.AppendLine($"{ci}partial class {className}");
        sb.AppendLine($"{ci}{{");
        foreach (var ne in named)
            sb.AppendLine($"{ci}    internal {Global(ne.Type)} {ne.Name} = null!;");
        if (named.Count > 0)
            sb.AppendLine();
        sb.AppendLine($"{ci}    private bool __contentLoaded;");
        sb.AppendLine();
        sb.AppendLine($"{ci}    internal void InitializeComponent()");
        sb.AppendLine($"{ci}    {{");
        sb.AppendLine($"{ci}        if (__contentLoaded) return;");
        sb.AppendLine($"{ci}        __contentLoaded = true;");
        sb.Append(ctx.Body);
        sb.AppendLine($"{ci}    }}");

        if (ctx.UsesConverter)
        {
            // The (hand-written, AOT-clean) converter ladder for typed literals. No reflection except the
            // named-color/TypeDescriptor edges in the ladder itself (tracked for later AOT-hardening).
            sb.AppendLine();
            sb.AppendLine($"{ci}    private static object? __ConvertXamlValue(global::System.Type targetType, string text)");
            sb.AppendLine($"{ci}        => global::Cursorial.UI.Xaml.XamlConverters.For(targetType) is {{ }} __c");
            sb.AppendLine($"{ci}            ? __c.ConvertFromString(text, new global::Cursorial.UI.Xaml.XamlValueContext(");
            sb.AppendLine($"{ci}                global::System.Globalization.CultureInfo.InvariantCulture, null, targetType, null, 0, 0))");
            sb.AppendLine($"{ci}            : text;");
        }

        sb.AppendLine($"{ci}}}");
        if (ns is not null)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitObject(Context c, int objectIndex, string varExpr, bool isRoot, bool hasScope)
    {
        ref readonly var obj = ref c.Doc.Objects[objectIndex];

        if (!isRoot)
        {
            var typeSymbol = TypeSymbolOf(c.Doc, obj.TypeId);
            if (typeSymbol is null)
            {
                c.Line($"// TODO X5: unresolved element type (object {objectIndex})");
                return;
            }
            c.Line($"var {varExpr} = new {Global(typeSymbol)}();");
        }

        for (int m = obj.MemberStart; m < obj.MemberStart + obj.MemberCount; m++)
        {
            ref readonly var member = ref c.Doc.Members[m];

            if (member.Kind == XamlValueKind.Directive)
            {
                if (member.DirectiveKind == (int)XamlDirectiveKind.Name && hasScope)
                {
                    var name = c.Doc.Strings[member.ValueIndex];
                    c.Line($"this.{name} = {varExpr};");
                    c.Line($"__scope.Register(\"{name}\", {varExpr});");
                }
                continue; // x:Class/x:Key/x:DataType: no lowered effect here
            }

            var xm = member.MemberId >= 0 ? c.Doc.ResolvedMembers[member.MemberId] : null;
            if (xm is null)
                continue;

            switch (member.Kind)
            {
                case XamlValueKind.Text:
                    EmitScalarAssign(c, varExpr, xm, c.Doc.Strings[member.ValueIndex]);
                    break;

                case XamlValueKind.Object:
                {
                    var childVar = c.NextVar();
                    EmitObject(c, member.ValueIndex, childVar, isRoot: false, hasScope);
                    EmitChildAssign(c, varExpr, xm, childVar, single: true);
                    break;
                }

                case XamlValueKind.Items:
                {
                    int childIndex = member.ValueIndex;
                    for (int i = 0; i < member.ItemCount; i++)
                    {
                        var childVar = c.NextVar();
                        EmitObject(c, childIndex, childVar, isRoot: false, hasScope);
                        EmitChildAssign(c, varExpr, xm, childVar, single: false);
                        childIndex += c.Doc.Objects[childIndex].SubtreeLength; // depth-first contiguous
                    }
                    break;
                }

                default:
                    c.Line($"// TODO X5: member '{xm.Name}' kind {member.Kind} not yet lowered");
                    break;
            }
        }
    }

    // A Text value: an object/string member takes the string literal directly; any other typed member runs
    // the (hand-written, AOT-clean) converter ladder via the emitted __ConvertXamlValue helper (X5.1).
    private static void EmitScalarAssign(Context c, string varExpr, XamlMember xm, string text)
    {
        string valueExpr;
        if (IsObjectOrString(xm.ValueType))
        {
            valueExpr = $"\"{Escape(text)}\"";
        }
        else if (ValueTypeSymbol(xm.ValueType) is { } valueType)
        {
            c.UsesConverter = true;
            valueExpr = $"__ConvertXamlValue(typeof({Global(valueType)}), \"{Escape(text)}\")";
        }
        else
        {
            c.Line($"// TODO X5: unresolved value type for {xm.Name}=\"{Escape(text)}\"");
            return;
        }

        if (RegisteredOwner(xm) is { } owner)
            // SetValue takes object? — no cast needed.
            c.Line($"{varExpr}.SetValue({Global(owner)}.{xm.Name}Property, {valueExpr});");
        else if (IsObjectOrString(xm.ValueType))
            c.Line($"{varExpr}.{xm.Name} = {valueExpr};");
        else
            // CLR setter wants the property type — cast the converter's object? result.
            c.Line($"{varExpr}.{xm.Name} = ({Global(ValueTypeSymbol(xm.ValueType)!)}){valueExpr}!;");
    }

    // A child element value: a registered-collection content member fills via Add; a single member is set
    // (SetValue for a UIProperty, else the CLR setter).
    private static void EmitChildAssign(Context c, string varExpr, XamlMember xm, string childVar, bool single)
    {
        if (!single)
        {
            c.Line($"{varExpr}.{xm.Name}.Add({childVar});");
            return;
        }

        if (RegisteredOwner(xm) is { } owner)
            c.Line($"{varExpr}.SetValue({Global(owner)}.{xm.Name}Property, {childVar});");
        else
            c.Line($"{varExpr}.{xm.Name} = {childVar};");
    }

    private static INamedTypeSymbol? RegisteredOwner(XamlMember member) => member.Property as INamedTypeSymbol;

    private static bool IsObjectOrString(IXamlType valueType)
        => valueType is RoslynXamlType { Symbol.SpecialType: SpecialType.System_Object or SpecialType.System_String };

    private static ITypeSymbol? ValueTypeSymbol(IXamlType valueType)
        => valueType is RoslynXamlType { Symbol: { } symbol } ? symbol : null;

    private static INamedTypeSymbol? TypeSymbolOf(XamlDocument document, int typeId)
        => typeId >= 0 && document.ResolvedTypes[typeId]?.ClrType is RoslynXamlType { Symbol: INamedTypeSymbol s } ? s : null;

    private static string Global(ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string Escape(string text) => text.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed class Context(XamlDocument document, string indent)
    {
        public XamlDocument Doc { get; } = document;
        public StringBuilder Body { get; } = new();
        public bool UsesConverter { get; set; }
        private int _counter;

        public string NextVar() => $"__e{_counter++}";

        public void Line(string statement) => Body.AppendLine(indent + statement);
    }
}
