using System.Collections.Generic;
using System.Linq;
using System.Text;

using Cursorial.UI.Xaml; // frontend node graph (internals via InternalsVisibleTo)

using Microsoft.CodeAnalysis;

namespace Cursorial.UI.Xaml.Generator;

/// <summary>
/// WS-X5 — the full-lowering code-behind generator. Where <see cref="CodeBehindEmitter"/> (X4 v1) emits an
/// <c>InitializeComponent</c> that calls the runtime loader, this emits the object graph as straight-line
/// C# — element construction, property/collection assignment, x:Name fields — so there is NO runtime parse
/// or reflection (the reflection-free / zero-AOT-warning route). Driven by the symbol-backed parse
/// (<see cref="RoslynXamlMetadata"/>) so resolved types/members carry their Roslyn symbols.
/// </summary>
/// <remarks>
/// SPINE scope (this workstream): element construction, registered-<c>UIProperty</c> <c>SetValue</c> and CLR
/// property sets for <c>object</c>/<c>string</c> values, content-property single + collection assignment, and
/// typed <c>x:Name</c> fields + name scope. Value conversion (typed literals), attached properties, events,
/// markup extensions, templates, and resources are later X5 workstreams — a member this spine can't yet
/// lower is emitted as a <c>// TODO X5</c> marker rather than wrong code.
/// </remarks>
internal static class LoweringEmitter
{
    public static LoweringResult? Emit(XamlDocument document, string xamlPath, XamlSymbolResolver resolver)
    {
        if (!document.HasObjects)
            return null;

        var (rootClass, named) = CodeBehindEmitter.Collect(document);
        if (rootClass is not { Length: > 0 })
            return null;

        int dot = rootClass.LastIndexOf('.');
        string? ns = dot > 0 ? rootClass.Substring(0, dot) : null;
        string className = dot > 0 ? rootClass.Substring(dot + 1) : rootClass;
        string indent = ns is null ? "    " : "        ";

        var ctx = new Context(document, indent, resolver);

        // Build the InitializeComponent body first (it determines whether a name scope is needed).
        if (named.Count > 0)
        {
            ctx.Line("var __scope = new global::Cursorial.UI.NameScopeDictionary();");
            ctx.Line("global::Cursorial.UI.NameScope.SetNameScope(this, __scope);");
        }
        EmitObject(ctx, objectIndex: 0, varExpr: "this", isRoot: true, hasScope: named.Count > 0, dataType: null);

        // {StaticResource} resolves EAGERLY but only once the whole tree is built + attached and every
        // <X.Resources> is populated — for a self-contained inline document the lexical scope chain IS the
        // live ancestor chain, so el.FindResource (a throw-on-miss live walk, matching the loader) is faithful.
        // Deferring to the end of InitializeComponent is the single point where both invariants hold.
        EmitDeferredStaticResources(ctx);

        // Template factory local functions go at the end of InitializeComponent (hoisted — the
        // FuncTemplateContent(...) references emitted above resolve to them).
        foreach (var factory in ctx.Factories)
            ctx.Body.Append(factory);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Cursorial.UI.Xaml.Generator — full-lowering code-behind (WS-X5)");
        sb.AppendLine($"// source: {xamlPath}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        string ci = ns is null ? string.Empty : "    ";
        sb.AppendLine($"{ci}partial class {className}");
        sb.AppendLine($"{ci}{{");
        foreach (var ne in named)
            sb.AppendLine($"{ci}    internal {Global(ne.Type)} {ne.Name} = null!;");
        if (named.Count > 0)
            sb.AppendLine();
        sb.AppendLine($"{ci}    private bool __contentLoaded;");
        sb.AppendLine();
        sb.AppendLine($"{ci}    internal void InitializeComponent()");
        sb.AppendLine($"{ci}    {{");
        sb.AppendLine($"{ci}        if (__contentLoaded) return;");
        sb.AppendLine($"{ci}        __contentLoaded = true;");
        sb.Append(ctx.Body);
        sb.AppendLine($"{ci}    }}");

        if (ctx.UsesConverter)
        {
            // The (hand-written, AOT-clean) converter ladder for typed literals. No reflection except the
            // named-color/TypeDescriptor edges in the ladder itself (tracked for later AOT-hardening).
            sb.AppendLine();
            sb.AppendLine($"{ci}    private static object? __ConvertXamlValue(global::System.Type targetType, string text)");
            sb.AppendLine($"{ci}        => global::Cursorial.UI.Xaml.XamlConverters.For(targetType) is {{ }} __c");
            sb.AppendLine($"{ci}            ? __c.ConvertFromString(text, new global::Cursorial.UI.Xaml.XamlValueContext(");
            sb.AppendLine($"{ci}                global::System.Globalization.CultureInfo.InvariantCulture, null, targetType, null, 0, 0))");
            sb.AppendLine($"{ci}            : text;");
        }

        sb.AppendLine($"{ci}}}");
        if (ns is not null)
            sb.AppendLine("}");

        return new LoweringResult(sb.ToString(), ctx.Unlowered);
    }

    private static void EmitObject(Context c, int objectIndex, string varExpr, bool isRoot, bool hasScope, INamedTypeSymbol? dataType)
    {
        ref readonly var obj = ref c.Doc.Objects[objectIndex];
        c.CurrentLineInfo = obj.PackedLineInfo;

        var objType = TypeSymbolOf(c.Doc, obj.TypeId);

        // Init-only CLR value members (e.g. SolidColorBrush.Color) can't be set post-construction (CS8852) — they
        // go in the construction object initializer. Pre-scan for them so the `new T { … }` carries them and the
        // member loop skips them. (The root is `this` — already constructed — so its init-only members can't use
        // an initializer; they fall to the member loop's ClrSetBlocked → TODO.)
        var initMembers = isRoot ? null : ScanInitOnlyMembers(c, in obj, objType);

        if (!isRoot)
        {
            if (objType is null)
            {
                c.Todo($"unresolved element type (object {objectIndex})");
                return;
            }
            var initializer = initMembers is { Entries.Count: > 0 } ? $" {{ {string.Join(", ", initMembers.Entries)} }}" : "()";
            c.Line($"var {varExpr} = new {Global(objType)}{initializer};");
        }

        // An x:DataType on this object establishes the compiled-binding source type for its whole subtree
        // (B184/B3); otherwise the enclosing scope's type carries down.
        dataType = XamlDataTypeScope.ForObject(c.Doc, in obj, c.Resolver) ?? dataType;

        for (int m = obj.MemberStart; m < obj.MemberStart + obj.MemberCount; m++)
        {
            ref readonly var member = ref c.Doc.Members[m];
            c.CurrentLineInfo = member.PackedLineInfo;
            c.CurrentObjectType = objType; // re-assert per member (child recursion clobbers it)

            if (initMembers is not null && initMembers.Indices.Contains(m))
                continue; // already emitted in the construction object initializer

            if (member.Kind == XamlValueKind.Directive)
            {
                if (member.DirectiveKind == (int)XamlDirectiveKind.Name)
                {
                    var name = c.Doc.Strings[member.ValueIndex];
                    if (c.TemplateContextVar is { } ctx)
                        // Inside a template: register into the per-build template name scope, never the document scope.
                        c.Line($"{ctx}.RegisterName(\"{name}\", {varExpr});");
                    else if (hasScope)
                    {
                        c.Line($"this.{name} = {varExpr};");
                        c.Line($"__scope.Register(\"{name}\", {varExpr});");
                    }
                }
                continue; // x:Class/x:Key/x:DataType: no lowered effect here
            }

            var xm = member.MemberId >= 0 ? c.Doc.ResolvedMembers[member.MemberId] : null;
            if (xm is null)
                continue;

            switch (member.Kind)
            {
                case XamlValueKind.Text:
                    EmitScalarAssign(c, varExpr, xm, c.Doc.Strings[member.ValueIndex]);
                    break;

                case XamlValueKind.Object:
                {
                    var childVar = c.NextVar();
                    EmitObject(c, member.ValueIndex, childVar, isRoot: false, hasScope, dataType);
                    EmitChildAssign(c, varExpr, xm, childVar, member.ValueIndex, single: true);
                    break;
                }

                case XamlValueKind.Items:
                {
                    int childIndex = member.ValueIndex;
                    for (int i = 0; i < member.ItemCount; i++)
                    {
                        var childVar = c.NextVar();
                        EmitObject(c, childIndex, childVar, isRoot: false, hasScope, dataType);
                        EmitChildAssign(c, varExpr, xm, childVar, childIndex, single: false);
                        childIndex += c.Doc.Objects[childIndex].SubtreeLength; // depth-first contiguous
                    }
                    break;
                }

                case XamlValueKind.Extension:
                    EmitExtensionAssign(c, varExpr, xm, in c.Doc.Extensions[member.ValueIndex], dataType);
                    break;

                case XamlValueKind.Deferred:
                {
                    // A template body (ControlTemplate/DataTemplate Content): lower the slice to a FuncTemplateContent
                    // factory built fresh per instantiation, and assign it to the ITemplateContent member.
                    var factory = EmitTemplateFactory(c, member.ValueIndex, hasScope);
                    var content = $"new global::Cursorial.UI.Controls.FuncTemplateContent({factory})";
                    if (RegisteredOwner(xm) is { } owner)
                        c.Line($"{varExpr}.SetValue({Global(owner)}.{xm.Name}Property, {content});");
                    else
                        c.Line($"{varExpr}.{xm.Name} = {content};");
                    break;
                }

                case XamlValueKind.Event:
                    // Click="OnClick" → `__e.Click += this.OnClick;`. The handler is resolved at the consumer's
                    // compile (a missing/mismatched handler is a CS error). The runtime loader no-ops events at
                    // X1, so lowering is strictly more capable here.
                    c.Line($"{varExpr}.{xm.Name} += this.{c.Doc.Strings[member.ValueIndex]};");
                    break;

                case XamlValueKind.Folded:
                    // Under FoldConstants=false the only Folded members are the intrinsic extensions:
                    // {x:Null} (a null constant) and {x:Static} (a XamlStaticReference carrying the member path).
                    EmitFoldedAssign(c, varExpr, xm, c.Doc.Constants[member.ValueIndex]);
                    break;

                default:
                    c.Todo($"member '{xm.Name}' kind {member.Kind} not yet lowered");
                    break;
            }
        }
    }

    // Lowers a deferred template body (the slice rooted at sliceHead — a single template-root object) to a static
    // local function `UIElement __FactoryN(TemplateBuildContext __ctx)` that builds a fresh subtree each call,
    // registering x:Name parts into __ctx's template name scope. Returns the factory name (wrapped in a
    // FuncTemplateContent by the caller). The factory is accumulated and appended at the end of InitializeComponent
    // (a local function is hoisted, so the forward reference resolves). Nested templates flatten into sibling factories.
    private static string EmitTemplateFactory(Context c, int sliceHead, bool hasScope)
    {
        var factoryName = c.NextFactory();
        var rootVar = c.NextVar();

        // Redirect emission into the factory body + enter template mode (x:Name → __ctx.RegisterName, {StaticResource}
        // → TODO since there's no end-of-tree FindResource anchor). Save/restore for correct nesting.
        var bodyBuf = new StringBuilder();
        var savedBuffer = c.SwapBuffer(bodyBuf);
        var savedInTemplate = c.InTemplate;
        var savedCtxVar = c.TemplateContextVar;
        c.InTemplate = true;
        c.TemplateContextVar = "__ctx";

        EmitObject(c, sliceHead, rootVar, isRoot: false, hasScope, dataType: null);

        c.InTemplate = savedInTemplate;
        c.TemplateContextVar = savedCtxVar;
        c.SwapBuffer(savedBuffer);

        var fn = new StringBuilder();
        fn.AppendLine($"{c.Indent}static global::Cursorial.UI.UIElement {factoryName}(global::Cursorial.UI.Controls.TemplateBuildContext __ctx)");
        fn.AppendLine($"{c.Indent}{{");
        fn.Append(bodyBuf);
        fn.AppendLine($"{c.Indent}    return {rootVar};");
        fn.AppendLine($"{c.Indent}}}");
        c.Factories.Add(fn.ToString());

        return factoryName;
    }

    // Pre-scans an object's Text/Folded members for init-only CLR value properties (settable only in an object
    // initializer). Returns the initializer entries (`Prop = expr`) + the member indices to skip in the main loop.
    private static InitOnlyScan ScanInitOnlyMembers(Context c, in ObjectRecord obj, INamedTypeSymbol? objType)
    {
        var scan = new InitOnlyScan();
        if (objType is null)
            return scan;

        for (int m = obj.MemberStart; m < obj.MemberStart + obj.MemberCount; m++)
        {
            ref readonly var member = ref c.Doc.Members[m];
            if (member.Kind is not (XamlValueKind.Text or XamlValueKind.Folded))
                continue;

            var xm = member.MemberId >= 0 ? c.Doc.ResolvedMembers[member.MemberId] : null;
            if (xm is null || RegisteredOwner(xm) is not null) // a UIProperty uses SetValue, never an initializer
                continue;

            if (XamlDataTypeScope.FindMember(objType, xm.Name) is not { } sym || !XamlDataTypeScope.IsInitOnlySettable(sym))
                continue;

            var expr = member.Kind == XamlValueKind.Text
                           ? ScalarTypedExpr(c, xm, c.Doc.Strings[member.ValueIndex])
                           : FoldedValueExpr(c, c.Doc.Constants[member.ValueIndex]);

            if (expr is null) // unresolved — let the member loop TODO it (don't skip)
                continue;

            scan.Entries.Add($"{xm.Name} = {expr}");
            scan.Indices.Add(m);
        }

        return scan;
    }

    // A Text value: an object/string member takes the string literal directly; any other typed member runs
    // the (hand-written, AOT-clean) converter ladder via the emitted __ConvertXamlValue helper (X5.1).
    // (Init-only CLR targets are set in the construction object initializer, NOT here — see EmitObject.)
    private static void EmitScalarAssign(Context c, string varExpr, XamlMember xm, string text)
    {
        if (RegisteredOwner(xm) is { } owner)
        {
            // SetValue takes object? — no cast needed.
            if (ScalarConvertExpr(c, xm, text) is { } raw)
                c.Line($"{varExpr}.SetValue({Global(owner)}.{xm.Name}Property, {raw});");
            else
                c.Todo($"unresolved value type for {xm.Name}=\"{Escape(text)}\"");
            return;
        }

        if (ClrSetBlocked(c, xm.Name))
        {
            c.Todo($"CLR property '{xm.Name}' is init-only/read-only — can't be set post-construction (set on the root, or a missed initializer)");
            return;
        }

        if (ScalarTypedExpr(c, xm, text) is { } typed)
            c.Line($"{varExpr}.{xm.Name} = {typed};");
        else
            c.Todo($"unresolved value type for {xm.Name}=\"{Escape(text)}\"");
    }

    // The object?-typed expression for a Text value (a string literal, or the converter call). Null = unresolved.
    private static string? ScalarConvertExpr(Context c, XamlMember xm, string text)
    {
        if (IsObjectOrString(xm.ValueType))
            return $"\"{Escape(text)}\"";

        if (ValueTypeSymbol(xm.ValueType) is { } valueType)
        {
            c.UsesConverter = true;
            return $"__ConvertXamlValue(typeof({Global(valueType)}), \"{Escape(text)}\")";
        }

        return null;
    }

    // The typed (cast) form for a CLR setter / object initializer (the converter's object? cast to the prop type).
    private static string? ScalarTypedExpr(Context c, XamlMember xm, string text)
    {
        if (ScalarConvertExpr(c, xm, text) is not { } raw)
            return null;

        return IsObjectOrString(xm.ValueType) ? raw : $"({Global(ValueTypeSymbol(xm.ValueType)!)}){raw}!";
    }

    // True only when the property is POSITIVELY known non-writable post-construction (init-only / read-only). A
    // symbol-walk miss keeps the current direct-set emit (avoids false TODOs for properties the walk doesn't surface).
    private static bool ClrSetBlocked(Context c, string name)
        => c.CurrentObjectType is { } t && XamlDataTypeScope.FindMember(t, name) is { } m && !XamlDataTypeScope.IsWritable(m);

    // A child element value: a ResourceDictionary member fills via Add(key, value) (the get-object dictionary,
    // keyed by x:Key); a registered-collection content member fills via Add(item); a single member is set
    // (SetValue for a UIProperty, else the CLR setter).
    private static void EmitChildAssign(Context c, string varExpr, XamlMember xm, string childVar, int childObjectIndex, bool single)
    {
        if (IsResourceDictionaryMember(xm))
        {
            EmitResourceEntry(c, varExpr, xm, childObjectIndex, childVar);
            return;
        }

        if (!single)
        {
            c.Line($"{varExpr}.{xm.Name}.Add({childVar});");
            return;
        }

        if (RegisteredOwner(xm) is { } owner)
            c.Line($"{varExpr}.SetValue({Global(owner)}.{xm.Name}Property, {childVar});");
        else
            c.Line($"{varExpr}.{xm.Name} = {childVar};");
    }

    // A keyed resource entry: read the child's x:Key directive and emit `parent.<Member>.Add("key", child)`
    // (the Resources getter is a get-object dictionary — read it, never assign). A {x:Type}/{x:Static}/escaped
    // key (anything not a plain string literal) is deferred to a // TODO X5; so is a key-less entry.
    private static void EmitResourceEntry(Context c, string varExpr, XamlMember xm, int childObjectIndex, string childVar)
    {
        if (ResourceKeyOf(c, childObjectIndex) is not { } key)
        {
            c.Todo($"resource entry in '{xm.Name}' has no plain-string x:Key (markup-extension keys not yet lowered)");
            return;
        }

        c.Line($"{varExpr}.{xm.Name}.Add(\"{Escape(key)}\", {childVar});");
    }

    // The plain-string x:Key on an object (the dictionary key), or null when absent / an extension-syntax key.
    private static string? ResourceKeyOf(Context c, int objectIndex)
    {
        ref readonly var obj = ref c.Doc.Objects[objectIndex];

        for (int m = obj.MemberStart; m < obj.MemberStart + obj.MemberCount; m++)
        {
            ref readonly var member = ref c.Doc.Members[m];

            if (member.Kind == XamlValueKind.Directive && member.DirectiveKind == (int) XamlDirectiveKind.Key)
            {
                var key = c.Doc.Strings[member.ValueIndex];
                return key.StartsWith("{", System.StringComparison.Ordinal) ? null : key; // an extension key isn't a literal
            }
        }

        return null;
    }

    private static bool IsResourceDictionaryMember(XamlMember xm)
        => ValueTypeSymbol(xm.ValueType) is INamedTypeSymbol s && SymbolXamlModel.IsResourceDictionary(s);

    // {x:Null} → null; {x:Static Type.Member} → the resolved static reference (global::Type.Member).
    // (Init-only CLR targets are set in the construction object initializer, NOT here — see EmitObject.)
    private static void EmitFoldedAssign(Context c, string varExpr, XamlMember xm, object? constant)
    {
        if (FoldedValueExpr(c, constant) is not { } valueExpr)
        {
            c.Todo($"folded value for {xm.Name} ({constant?.GetType().Name ?? "null"})");
            return;
        }

        if (RegisteredOwner(xm) is { } owner)
        {
            c.Line($"{varExpr}.SetValue({Global(owner)}.{xm.Name}Property, {valueExpr});");
            return;
        }

        if (ClrSetBlocked(c, xm.Name))
        {
            c.Todo($"CLR property '{xm.Name}' is init-only/read-only — can't be set post-construction");
            return;
        }

        c.Line($"{varExpr}.{xm.Name} = {valueExpr};");
    }

    // The C# expression for a folded constant: null, or {x:Static}'s resolved global:: reference. Null = not handled.
    private static string? FoldedValueExpr(Context c, object? constant) => constant switch
    {
        null => "null",
        XamlStaticReference staticRef => ResolveStaticPath(c, staticRef.MemberPath),
        _ => null, // not expected under FoldConstants=false
    };

    // ── {Binding} (B3a — the compiled lane) ──────────────────────────────────────────────────────

    private static void EmitExtensionAssign(Context c, string varExpr, XamlMember xm, in ExtensionRecord ext, INamedTypeSymbol? dataType)
    {
        switch (ext.Kind)
        {
            case ExtensionKind.Binding when c.Doc.ParsedExtensions[ext.Payload] is { } node:
                EmitBinding(c, varExpr, xm, node, dataType);
                return;

            case ExtensionKind.DynamicResource:
                EmitDynamicResource(c, varExpr, xm, in ext);
                return;

            case ExtensionKind.StaticResource:
                EmitStaticResource(c, varExpr, xm, in ext);
                return;

            // TemplateBinding lowering is a later X5.4 sub-workstream (templates).
            default:
                c.Todo($"extension {ext.Kind} for '{xm.Name}' not yet lowered");
                return;
        }
    }

    // {DynamicResource Key} → ResourceExtensions.SetResourceReference(element, Owner.FooProperty, key): a live
    // producer that re-resolves against the element's ancestor chain on attach (no eager-resolution timing
    // problem — works inline AND inside templates). Requires a registered StyledProperty<T> target (the runtime
    // handler rejects direct/attached); a literal key only (a nested-extension key is deferred to a later cut).
    private static void EmitDynamicResource(Context c, string varExpr, XamlMember xm, in ExtensionRecord ext)
    {
        if (ext.PayloadIsParsedExtension)
        {
            c.Todo($"{{DynamicResource}} with a markup-extension key for '{xm.Name}' not yet lowered");
            return;
        }

        if (!XamlDataTypeScope.IsUIElement(c.CurrentObjectType))
        {
            c.Todo($"{{DynamicResource}} on a non-UIElement target ('{xm.Name}') not yet lowered");
            return;
        }

        if (RegisteredOwner(xm) is not { } owner || !XamlDataTypeScope.IsStyledProperty(owner, xm.Name))
        {
            c.Todo($"{{DynamicResource}} target '{xm.Name}' is not a styled UIProperty (direct/attached unsupported)");
            return;
        }

        var key = c.Doc.Strings[ext.Payload];
        // SetResourceReference<T> infers T from the StyledProperty<T> field; call it statically (no using).
        c.Line($"global::Cursorial.UI.ResourceExtensions.SetResourceReference({varExpr}, {Global(owner)}.{xm.Name}Property, \"{Escape(key)}\");");
    }

    // {StaticResource Key} — eager, but deferred to end-of-InitializeComponent (see EmitDeferredStaticResources):
    // record (element, target, key). A markup-extension key, or a StaticResource inside a template factory
    // (where there is no end-of-tree FindResource anchor — it needs the captured lexical scope), stays a // TODO.
    private static void EmitStaticResource(Context c, string varExpr, XamlMember xm, in ExtensionRecord ext)
    {
        if (ext.PayloadIsParsedExtension)
        {
            c.Todo($"{{StaticResource}} with a markup-extension key for '{xm.Name}' not yet lowered");
            return;
        }

        if (c.InTemplate)
        {
            c.Todo($"{{StaticResource}} for '{xm.Name}' inside a template not yet lowered (needs the captured lexical scope)");
            return;
        }

        // FindResource is a UIElement extension; a {StaticResource} on a non-element object (e.g. a brush inside a
        // resource value) can't use the end-of-tree FindResource anchor — bail rather than emit an uncompilable call.
        if (!XamlDataTypeScope.IsUIElement(c.CurrentObjectType))
        {
            c.Todo($"{{StaticResource}} on a non-UIElement target ('{xm.Name}') not yet lowered");
            return;
        }

        var key = c.Doc.Strings[ext.Payload];
        var owner = RegisteredOwner(xm);
        // For a CLR (non-UIProperty) target, remember the value type so the assignment casts FindResource's
        // object? to the property type — needed even for a `string` target (object? → string is not implicit).
        var clrType = owner is null ? ValueTypeSymbol(xm.ValueType) : null;
        c.StaticResources.Add(new StaticResourceResolution(varExpr, owner, xm.Name, key, clrType));
    }

    // Emits the recorded {StaticResource} resolutions at the end of InitializeComponent. By here the whole tree
    // is constructed + attached and every <X.Resources> is populated, so el.FindResource walks the full ancestor
    // chain (throw-on-miss, matching the loader's eager resolution). Lexical == live for an inline document.
    private static void EmitDeferredStaticResources(Context c)
    {
        if (c.StaticResources.Count == 0)
            return;

        c.Line("// X5.4 — resolve {StaticResource}s now the tree is built + attached and resources are populated.");
        foreach (var sr in c.StaticResources)
        {
            string find = $"global::Cursorial.UI.ResourceExtensions.FindResource({sr.Var}, \"{Escape(sr.Key)}\")";

            if (sr.Owner is { } owner)
                c.Line($"{sr.Var}.SetValue({Global(owner)}.{sr.Property}Property, {find});");
            else if (sr.ClrType is { } ct)
                c.Line($"{sr.Var}.{sr.Property} = ({Global(ct)}){find}!;");
            else
                c.Line($"{sr.Var}.{sr.Property} = {find};");
        }
    }

    // B3a/B3b — {Binding} lowering. The compiled lane (zero reflection, AOT-clean) is taken for an
    // x:DataType-scoped, DataContext-relative, single-hop binding; everything else falls back to a faithful
    // reflective `new Binding(...)` (the plan's "graceful reflective fallback" — the binding still works, just
    // through the reflective engine, which surfaces an AOT warning pointing at the binding to fix). Only a
    // Converter-bearing binding (needs eager resource/static resolution, deferred with resources) or an
    // unsupported RelativeSource stays a // TODO X5.
    private static void EmitBinding(Context c, string varExpr, XamlMember xm, MarkupExtensionNode node, INamedTypeSymbol? dataType)
    {
        // A binding target must be a registered UIProperty — the runtime handler enforces the same (X119).
        if (RegisteredOwner(xm) is not { } owner)
        {
            c.Todo($"binding target '{xm.Name}' is not a bindable UIProperty");
            return;
        }

        if (TryEmitCompiledBinding(c, varExpr, owner, xm, node, dataType))
            return;

        EmitReflectiveBinding(c, varExpr, owner, xm, node);
    }

    private static bool TryEmitCompiledBinding(
        Context c, string varExpr, INamedTypeSymbol owner, XamlMember xm, MarkupExtensionNode node, INamedTypeSymbol? dataType)
    {
        if (dataType is null)
            return false;

        // Only a plain DataContext-relative binding is x:DataType-rooted; any anchor/converter/format/fallback
        // arg changes semantics this lane doesn't yet reproduce — bail so it isn't silently dropped.
        if (HasNamed(node, "Source") || HasNamed(node, "ElementName") || HasNamed(node, "RelativeSource") ||
            HasNamed(node, "Converter") || HasNamed(node, "StringFormat") || HasNamed(node, "FallbackValue"))
        {
            return false;
        }

        var path = BindingPathOf(node);
        if (string.IsNullOrEmpty(path) || path == ".")
            return false;

        // Single-hop only in B3a (multi-hop getter/steps + null-propagation is a later workstream).
        if (path!.IndexOf('.') >= 0 || path.IndexOf('[') >= 0 || path.IndexOf('(') >= 0)
            return false;

        if (CanonicalMode(node) is not { } modeName) // an unknown Mode token — bail to the reflective fallback
            return false;

        if (XamlDataTypeScope.FindMember(dataType, path) is not { IsStatic: false } leaf ||
            XamlDataTypeScope.MemberType(leaf) is not { } leafType ||
            !XamlDataTypeScope.IsReadable(leaf))
        {
            // A static-named path can't be `__s.Member` (CS0176) — bail to the reflective fallback (which
            // resolves instance-or-static identically to the runtime loader's reflective binding).
            return false;
        }

        string data = Global(dataType);
        string value = Global(leafType);
        string getter = $"static __s => __s.{path}";
        // A writable leaf gets a reverse setter (TwoWay/Default-on-a-two-way-property work); a read-only leaf
        // passes null (the engine degrades a TwoWay use to OneWay — B152), mirroring the reflective lane.
        string setter = XamlDataTypeScope.IsWritable(leaf) ? $"static (__s, __v) => __s.{path} = __v" : "null";
        string step = $"new global::Cursorial.UI.Data.CompiledPathStep(\"{Escape(path)}\", static __o => (object?)(({data}) __o!).{path})";

        c.Line(
            $"global::Cursorial.UI.Data.BindingOperations.Install({varExpr}, {Global(owner)}.{xm.Name}Property, " +
            $"new global::Cursorial.UI.Data.CompiledBinding<{data}, {value}>({getter}, {setter}, " +
            $"new global::Cursorial.UI.Data.CompiledPathStep[] {{ {step} }}, \"{Escape(path)}\"){Initializers(ModeInit(modeName))});");
        return true;
    }

    // The reflective fallback (B3b) — a faithful `new Binding(path) { … }` mirroring the runtime handler's
    // BuildBinding (Mode/ElementName/Source/StringFormat/FallbackValue/RelativeSource), minus Converter.
    private static void EmitReflectiveBinding(Context c, string varExpr, INamedTypeSymbol owner, XamlMember xm, MarkupExtensionNode node)
    {
        // A Converter needs eager resource/static resolution, which lowering doesn't do yet — defer (X5.4).
        if (HasNamed(node, "Converter"))
        {
            c.Todo($"{{Binding}} with a Converter for '{xm.Name}' not yet lowered (needs resource lowering)");
            return;
        }

        if (CanonicalMode(node) is not { } modeName)
        {
            c.Todo($"{{Binding}} with an unrecognized Mode for '{xm.Name}'");
            return;
        }

        if (RelativeSourceInit(node) is not { } relSource)
        {
            c.Todo($"{{Binding}} RelativeSource for '{xm.Name}' not supported in lowering (Self/TemplatedParent only)");
            return;
        }

        string path = Escape(BindingPathOf(node) ?? string.Empty);
        var inits = new List<string>(ModeInit(modeName))
        {
            relSource,
            StringInit("ElementName", NamedText(node, "ElementName")),
            StringInit("Source", NamedText(node, "Source")),       // mirrors the handler: Source = the bare string
            StringInit("StringFormat", NamedText(node, "StringFormat")),
            StringInit("FallbackValue", NamedText(node, "FallbackValue")),
        };

        c.Line(
            $"global::Cursorial.UI.Data.BindingOperations.Install({varExpr}, {Global(owner)}.{xm.Name}Property, " +
            $"new global::Cursorial.UI.Data.Binding(\"{path}\"){Initializers(inits)});");
    }

    // The binding path: the first positional argument, else the Path= named argument (mirrors the runtime handler).
    private static string? BindingPathOf(MarkupExtensionNode node)
        => node.PositionalArguments.Count > 0 && node.PositionalArguments[0].Text is { } p ? p : NamedText(node, "Path");

    private static bool HasNamed(MarkupExtensionNode node, string name) => node.FindNamed(name) is not null;

    private static string? NamedText(MarkupExtensionNode node, string name)
        => node.FindNamed(name) is { Text: { } t } ? t : null;

    private static string? FirstPositionalText(MarkupExtensionNode node)
        => node.PositionalArguments.Count > 0 ? node.PositionalArguments[0].Text : null;

    // The canonical BindingMode member name; "" for unspecified (Default — resolved at install, BD10); null for
    // an unrecognized token (the caller bails — the compiled path to the reflective fallback, the fallback to TODO).
    private static string? CanonicalMode(MarkupExtensionNode node)
    {
        if (NamedText(node, "Mode") is not { } text)
            return string.Empty;

        // BindingMode is a closed enum; match case-insensitively (WPF/Avalonia parity with the runtime handler).
        return text.ToLowerInvariant() switch
        {
            "default" => "Default",
            "oneway" => "OneWay",
            "twoway" => "TwoWay",
            "onetime" => "OneTime",
            "onewaytosource" => "OneWayToSource",
            _ => null,
        };
    }

    // The `Mode = BindingMode.X` initializer fragment for a carried mode ("" when unspecified ⇒ no fragment).
    private static IEnumerable<string> ModeInit(string modeName)
        => modeName.Length == 0 ? [] : [$"Mode = global::Cursorial.UI.Data.BindingMode.{modeName}"];

    private static string StringInit(string member, string? value)
        => value is null ? string.Empty : $"{member} = \"{Escape(value)}\"";

    // The `RelativeSource = …` fragment: "" not present; the Self/TemplatedParent fragment; null for an
    // unsupported mode (FindAncestor etc. — the caller TODOs), mirroring the handler's ParseRelativeSource.
    private static string? RelativeSourceInit(MarkupExtensionNode node)
    {
        if (node.FindNamed("RelativeSource") is not { } value)
            return string.Empty;

        string? mode = value.IsNested
            ? FirstPositionalText(value.Nested!) ?? NamedText(value.Nested!, "Mode")
            : value.Text;

        return mode switch
        {
            "TemplatedParent" => "RelativeSource = global::Cursorial.UI.Data.RelativeSource.TemplatedParent",
            "Self" => "RelativeSource = global::Cursorial.UI.Data.RelativeSource.Self",
            null when value.IsNested => "RelativeSource = global::Cursorial.UI.Data.RelativeSource.Self", // WPF default
            _ => null,
        };
    }

    // Joins non-empty object-initializer member assignments into a ` { a, b }` suffix, or "" when none.
    private static string Initializers(IEnumerable<string> members)
    {
        var present = members.Where(s => s.Length > 0).ToList();
        return present.Count == 0 ? string.Empty : " { " + string.Join(", ", present) + " }";
    }

    // Resolves an {x:Static Type.Member} path to a C# static reference. The type token (before the last dot)
    // is resolved through the same symbol resolver the parse used (default UI xmlns); the member is appended.
    private static string? ResolveStaticPath(Context c, string memberPath)
    {
        int dot = memberPath.LastIndexOf('.');
        if (dot <= 0)
            return null;

        var typeName = memberPath.Substring(0, dot);
        var member = memberPath.Substring(dot + 1);
        var typeSymbol = c.Resolver.Resolve(XamlSymbolResolver.CursorialUiNamespace, typeName, out _);
        return typeSymbol is null ? null : $"{Global(typeSymbol)}.{member}"; // Global() already prefixes global::
    }

    private static INamedTypeSymbol? RegisteredOwner(XamlMember member) => member.Property as INamedTypeSymbol;

    private static bool IsObjectOrString(IXamlType valueType)
        => valueType is RoslynXamlType { Symbol.SpecialType: SpecialType.System_Object or SpecialType.System_String };

    private static ITypeSymbol? ValueTypeSymbol(IXamlType valueType)
        => valueType is RoslynXamlType { Symbol: { } symbol } ? symbol : null;

    private static INamedTypeSymbol? TypeSymbolOf(XamlDocument document, int typeId)
        => typeId >= 0 && document.ResolvedTypes[typeId]?.ClrType is RoslynXamlType { Symbol: INamedTypeSymbol s } ? s : null;

    private static string Global(ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string Escape(string text) => text.Replace("\\", "\\\\").Replace("\"", "\\\"");

    // The result of an init-only member pre-scan: the object-initializer entries + the member indices to skip.
    private sealed class InitOnlyScan
    {
        public List<string> Entries { get; } = [];
        public HashSet<int> Indices { get; } = [];
    }

    private sealed class Context(XamlDocument document, string indent, XamlSymbolResolver resolver)
    {
        public XamlDocument Doc { get; } = document;
        public XamlSymbolResolver Resolver { get; } = resolver;
        public string Indent { get; } = indent;
        public StringBuilder Body { get; } = new();
        public bool UsesConverter { get; set; }
        public List<UnloweredMember> Unlowered { get; } = [];
        public List<StaticResourceResolution> StaticResources { get; } = [];

        /// <summary>The emitted template factory local functions, appended at the end of InitializeComponent (hoisted).</summary>
        public List<string> Factories { get; } = [];

        /// <summary>True while lowering inside a template factory (no end-of-tree FindResource anchor for {StaticResource}).</summary>
        public bool InTemplate { get; set; }

        /// <summary>The TemplateBuildContext var name while inside a template factory (x:Name → its RegisterName); null otherwise.</summary>
        public string? TemplateContextVar { get; set; }

        /// <summary>The type of the object whose members are currently being lowered — the receiver of resource extensions.</summary>
        public INamedTypeSymbol? CurrentObjectType { get; set; }

        /// <summary>The packed source position of the member currently being lowered — stamps any TODO note.</summary>
        public int CurrentLineInfo { get; set; }

        private int _counter;
        private int _factoryCounter;
        private StringBuilder? _current; // the emit target; null ⇒ Body (a template factory redirects via SwapBuffer)

        private StringBuilder Current => _current ?? Body;

        public string NextVar() => $"__e{_counter++}";

        public string NextFactory() => $"__Factory{_factoryCounter++}";

        /// <summary>Redirects <see cref="Line"/> to <paramref name="buffer"/> and returns the previous target (for restore).</summary>
        public StringBuilder SwapBuffer(StringBuilder buffer)
        {
            var prev = Current;
            _current = buffer;
            return prev;
        }

        public void Line(string statement) => Current.AppendLine(Indent + statement);

        /// <summary>
        /// Records a feature the full-lowering can't yet emit: leaves a visible <c>// TODO X5</c> marker in the
        /// generated code AND a note the generator surfaces as a build warning (so an opted-in <c>full</c> build
        /// never silently drops a member — the marker alone would be invisible at the call site).
        /// </summary>
        public void Todo(string message)
        {
            Line("// TODO X5: " + message);
            Unlowered.Add(new UnloweredMember(message, LineInfo.Line(CurrentLineInfo), LineInfo.Column(CurrentLineInfo)));
        }
    }

    /// <summary>The lowered source plus the members it couldn't emit (each a build-warning candidate).</summary>
    public readonly struct LoweringResult(string source, IReadOnlyList<UnloweredMember> unlowered)
    {
        public string Source { get; } = source;
        public IReadOnlyList<UnloweredMember> Unlowered { get; } = unlowered;
    }

    /// <summary>A member the full-lowering couldn't emit, with its 1-based source position (0 if unknown).</summary>
    public readonly struct UnloweredMember(string message, int line, int column)
    {
        public string Message { get; } = message;
        public int Line { get; } = line;
        public int Column { get; } = column;
    }

    // A {StaticResource} to resolve at end-of-InitializeComponent. Owner non-null ⇒ SetValue(Owner.<Prop>Property);
    // else a CLR set (cast to ClrType when non-null, i.e. a typed non-object/string CLR target).
    private readonly struct StaticResourceResolution(string var, INamedTypeSymbol? owner, string property, string key, ITypeSymbol? clrType)
    {
        public string Var { get; } = var;
        public INamedTypeSymbol? Owner { get; } = owner;
        public string Property { get; } = property;
        public string Key { get; } = key;
        public ITypeSymbol? ClrType { get; } = clrType;
    }
}
