using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;

namespace Cursorial.UI.Xaml.Generator;

/// <summary>
/// Emits the generated <c>IXamlTypeMetadataProvider</c> (design doc §4.9 / WS-X4.5) — the trim/AOT-clean
/// analog of <c>ReflectionXamlMetadata</c>, shaped exactly like the hand-written <c>HandBuiltMetadata</c>
/// exemplar. For the closed type set a document references it bakes, per type: the activation thunk
/// (<c>new T()</c>), the content property + collection flag, and the member table mirroring
/// <c>ReflectionXamlMetadata.BuildMember</c>'s ladder — a registered <c>UIProperty</c> (the
/// <c>&lt;Name&gt;Property</c> static field), a CLR property (setter/getter delegate), or an event. The
/// converter is emitted as a runtime <c>XamlConverters.For(typeof(...))</c> call, so it resolves
/// identically to the reflection provider (converter drift is impossible). No reflection, no
/// <c>System.Type</c> at generator time — only the consumer's <c>typeof</c>/field references.
/// </summary>
internal sealed class MetadataProviderEmitter
{
    private const string Ui = "https://cursorial.dev/ui";
    private const string Frontend = "global::Cursorial.UI.Xaml";

    // The loader's ContentPropertyTable, by base-type full name (most-derived first).
    private static readonly (string BaseType, string Property)[] ContentPropertyTable =
    {
        ("Cursorial.UI.Controls.ContentControl", "Content"),
        ("Cursorial.UI.Controls.Decorator", "Child"),
        ("Cursorial.UI.Popup", "Child"),
        ("Cursorial.UI.Controls.Panel", "Children"),
        ("Cursorial.UI.Controls.ControlTemplate", "Content"),
        ("Cursorial.UI.Controls.DataTemplate", "Content"),
        ("Cursorial.UI.Style", "Setters"),
        ("Cursorial.Drawing.Media.GradientBrush", "Stops"),
    };

    private readonly Compilation _compilation;

    public MetadataProviderEmitter(Compilation compilation) => _compilation = compilation;

    /// <summary>Emits the provider source for <paramref name="types"/> (resolved closed set), or null if empty.</summary>
    public string? Emit(IReadOnlyList<INamedTypeSymbol> types)
    {
        if (types.Count == 0)
            return null;

        // Deterministic order (display name) for stable output.
        var ordered = types
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>()
            .OrderBy(t => t.ToDisplayString(), System.StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Cursorial.UI.Xaml.Generator — generated metadata provider (WS-X4.5).");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("[assembly: " + Frontend + ".XamlMetadataProvider(typeof(Cursorial.UI.Xaml.Generated.__GeneratedXamlMetadata))]");
        sb.AppendLine();
        sb.AppendLine("namespace Cursorial.UI.Xaml.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    internal sealed class __GeneratedXamlMetadata : {Frontend}.IXamlTypeMetadataProvider");
        sb.AppendLine("    {");
        sb.AppendLine("        public static readonly __GeneratedXamlMetadata Instance = new();");
        sb.AppendLine();

        EmitTryGetType(sb, ordered);
        EmitNamespaceTables(sb, ordered);
        EmitKnownMemberNames(sb, ordered);

        foreach (var type in ordered)
            EmitType(sb, type);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private void EmitTryGetType(StringBuilder sb, List<INamedTypeSymbol> types)
    {
        sb.AppendLine($"        public {Frontend}.XamlTypeResolution TryGetType(string xmlNamespace, string localName)");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (!string.Equals(xmlNamespace, \"{Ui}\", global::System.StringComparison.Ordinal))");
        sb.AppendLine($"                return {Frontend}.XamlTypeResolution.NotFound();");
        sb.AppendLine("            return localName switch");
        sb.AppendLine("            {");
        foreach (var type in types)
            sb.AppendLine($"                \"{type.Name}\" => {Frontend}.XamlTypeResolution.Resolved({FieldName(type)}),");
        sb.AppendLine($"                _ => {Frontend}.XamlTypeResolution.NotFound(),");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private void EmitNamespaceTables(StringBuilder sb, List<INamedTypeSymbol> types)
    {
        var namespaces = types.Select(t => t.ContainingNamespace.ToDisplayString()).Distinct(System.StringComparer.Ordinal).OrderBy(n => n, System.StringComparer.Ordinal);
        var typeNames = types.Select(t => t.Name).Distinct(System.StringComparer.Ordinal).OrderBy(n => n, System.StringComparer.Ordinal);

        sb.AppendLine("        public string[] GetClrNamespaces(string xmlNamespace) =>");
        sb.AppendLine($"            string.Equals(xmlNamespace, \"{Ui}\", global::System.StringComparison.Ordinal) ? new[] {{ {string.Join(", ", namespaces.Select(n => $"\"{n}\""))} }} : global::System.Array.Empty<string>();");
        sb.AppendLine();
        sb.AppendLine("        public string[] GetKnownTypeNames(string xmlNamespace) =>");
        sb.AppendLine($"            string.Equals(xmlNamespace, \"{Ui}\", global::System.StringComparison.Ordinal) ? new[] {{ {string.Join(", ", typeNames.Select(n => $"\"{n}\""))} }} : global::System.Array.Empty<string>();");
        sb.AppendLine();
    }

    private void EmitKnownMemberNames(StringBuilder sb, List<INamedTypeSymbol> types)
    {
        sb.AppendLine("        public string[] GetKnownMemberNames(global::System.Type clrType)");
        sb.AppendLine("        {");
        foreach (var type in types)
        {
            var names = EnumerateMembers(type).Select(m => m.Name).Distinct(System.StringComparer.Ordinal).OrderBy(n => n, System.StringComparer.Ordinal);
            sb.AppendLine($"            if (clrType == typeof({Global(type)})) return new[] {{ {string.Join(", ", names.Select(n => $"\"{n}\""))} }};");
        }
        sb.AppendLine("            return global::System.Array.Empty<string>();");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private void EmitType(StringBuilder sb, INamedTypeSymbol type)
    {
        var field = FieldName(type);
        var members = EnumerateMembers(type).ToList();
        var contentProperty = ResolveContentProperty(type);
        var isCollection = contentProperty is not null && ContentIsCollection(type, contentProperty);

        sb.AppendLine($"        private static readonly {Frontend}.XamlType {field} = Build_{field}();");
        sb.AppendLine($"        private static {Frontend}.XamlType Build_{field}()");
        sb.AppendLine("        {");
        sb.AppendLine($"            var members = new global::System.Collections.Generic.Dictionary<string, {Frontend}.XamlMember>(global::System.StringComparer.Ordinal)");
        sb.AppendLine("            {");
        foreach (var member in members)
            sb.AppendLine("                " + EmitMember(type, member) + ",");
        sb.AppendLine("            };");
        sb.AppendLine($"            return new {Frontend}.XamlType(");
        sb.AppendLine($"                clrType: typeof({Global(type)}),");
        sb.AppendLine($"                activate: {(CanActivate(type) ? $"static () => new {Global(type)}()" : "null")},");
        sb.AppendLine($"                contentProperty: {(contentProperty is null ? "null" : $"\"{contentProperty}\"")},");
        sb.AppendLine($"                isCollection: {(isCollection ? "true" : "false")},");
        sb.AppendLine("                memberResolver: name => members.TryGetValue(name, out var m) ? m : null);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private string EmitMember(INamedTypeSymbol owner, MemberModel member)
    {
        var valueTypeOf = $"typeof({Global(member.ValueType)})";
        var converter = $"{Frontend}.XamlConverters.For({valueTypeOf})";

        if (member.IsEvent)
            return $"[\"{member.Name}\"] = new {Frontend}.XamlMember(\"{member.Name}\", {valueTypeOf}, isEvent: true)";

        if (member.RegisteredFieldOwner is not null)
        {
            // Registered UIProperty: property: <DeclaringType>.<Name>Property
            var prop = $"{Global(member.RegisteredFieldOwner)}.{member.Name}Property";
            return $"[\"{member.Name}\"] = new {Frontend}.XamlMember(\"{member.Name}\", {valueTypeOf}, property: {prop}, converter: {converter})";
        }

        // CLR property: setClr / get delegates.
        var setClr = member.CanWrite
            ? $"setClr: (t, v) => (({Global(owner)})t).{member.Name} = ({Global(member.ValueType)})v!"
            : null;
        var get = member.CanRead ? $"get: t => (({Global(owner)})t).{member.Name}" : null;
        var parts = new List<string> { $"\"{member.Name}\"", valueTypeOf };
        if (setClr is not null) parts.Add(setClr);
        if (get is not null) parts.Add(get);
        parts.Add($"converter: {converter}");
        return $"[\"{member.Name}\"] = new {Frontend}.XamlMember({string.Join(", ", parts)})";
    }

    // ── symbol analysis (mirrors ReflectionXamlMetadata) ──────────────────────────────────────────

    private IEnumerable<MemberModel> EnumerateMembers(INamedTypeSymbol type)
    {
        var seen = new HashSet<string>(System.StringComparer.Ordinal);
        for (INamedTypeSymbol? t = type; t is not null && t.SpecialType != SpecialType.System_Object; t = t.BaseType)
        {
            foreach (var symbol in t.GetMembers())
            {
                if (symbol.DeclaredAccessibility != Accessibility.Public || symbol.IsStatic)
                    continue;

                if (symbol is IPropertySymbol { IsIndexer: false } prop && seen.Add(prop.Name))
                {
                    var registeredOwner = FindRegisteredPropertyOwner(type, prop.Name);
                    yield return new MemberModel(prop.Name, prop.Type, prop.SetMethod is { DeclaredAccessibility: Accessibility.Public },
                        prop.GetMethod is { DeclaredAccessibility: Accessibility.Public }, IsEvent: false, registeredOwner);
                }
                else if (symbol is IEventSymbol evt && seen.Add(evt.Name))
                {
                    yield return new MemberModel(evt.Name, evt.Type, CanWrite: false, CanRead: false, IsEvent: true, RegisteredFieldOwner: null);
                }
            }
        }
    }

    // Finds the type that declares a `public static <name>Property` UIProperty-derived field (the registration convention).
    private INamedTypeSymbol? FindRegisteredPropertyOwner(INamedTypeSymbol type, string memberName)
    {
        var fieldName = memberName + "Property";
        for (INamedTypeSymbol? t = type; t is not null && t.SpecialType != SpecialType.System_Object; t = t.BaseType)
        {
            var field = t.GetMembers(fieldName).OfType<IFieldSymbol>()
                .FirstOrDefault(f => f.IsStatic && f.DeclaredAccessibility == Accessibility.Public && IsUIPropertyType(f.Type));
            if (field is not null)
                return t;
        }
        return null;
    }

    private static bool IsUIPropertyType(ITypeSymbol type)
    {
        for (var t = type; t is not null; t = t.BaseType)
        {
            var name = t.OriginalDefinition.ToDisplayString();
            if (name.StartsWith("Cursorial.UI.StyledProperty", System.StringComparison.Ordinal)
                || name.StartsWith("Cursorial.UI.DirectProperty", System.StringComparison.Ordinal)
                || name.StartsWith("Cursorial.UI.AttachedProperty", System.StringComparison.Ordinal)
                || name == "Cursorial.UI.UIProperty")
                return true;
        }
        return false;
    }

    private string? ResolveContentProperty(INamedTypeSymbol type)
    {
        // (1) An explicit [ContentProperty("Name")] attribute (matched by simple name).
        foreach (var attr in type.GetAttributes())
        {
            if (attr.AttributeClass?.Name == "ContentPropertyAttribute"
                && attr.ConstructorArguments.Length == 1
                && attr.ConstructorArguments[0].Value is string name && name.Length > 0)
                return name;
        }

        // (2) The known base-type table (most-derived first).
        for (INamedTypeSymbol? t = type; t is not null && t.SpecialType != SpecialType.System_Object; t = t.BaseType)
        {
            var full = t.ToDisplayString();
            foreach (var (baseType, property) in ContentPropertyTable)
                if (full == baseType)
                    return property;
        }
        return null;
    }

    private bool ContentIsCollection(INamedTypeSymbol type, string contentProperty)
    {
        var prop = EnumerateMembers(type).FirstOrDefault(m => m.Name == contentProperty);
        if (prop.Name is null || prop.ValueType is null)
            return false;
        var ct = prop.ValueType;
        if (ct.SpecialType == SpecialType.System_String || ct.SpecialType == SpecialType.System_Object)
            return false;
        if (ct.Name == "ITemplateContent")
            return false;
        return ImplementsIList(ct);
    }

    private static bool ImplementsIList(ITypeSymbol type)
    {
        foreach (var iface in type.AllInterfaces)
        {
            if (iface.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IList_T)
                return true;
            if (iface.ToDisplayString() == "System.Collections.IList")
                return true;
        }
        return type.ToDisplayString() == "System.Collections.IList";
    }

    private static bool CanActivate(INamedTypeSymbol type)
    {
        if (type.IsAbstract || type.TypeKind == TypeKind.Interface)
            return false;
        if (type.IsValueType)
            return type.OriginalDefinition.SpecialType != SpecialType.System_Nullable_T;
        return type.InstanceConstructors.Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);
    }

    private static string FieldName(INamedTypeSymbol type) => type.Name;

    private static string Global(ITypeSymbol type)
        => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private readonly record struct MemberModel(
        string Name, ITypeSymbol ValueType, bool CanWrite, bool CanRead, bool IsEvent, INamedTypeSymbol? RegisteredFieldOwner);
}
