using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;

namespace Cursorial.UI.Xaml.Generator;

/// <summary>
/// Emits the generated <c>IXamlTypeMetadataProvider</c> (design doc §4.9 / WS-X4.5) — the trim/AOT-clean
/// analog of <c>ReflectionXamlMetadata</c>, shaped exactly like the hand-written <c>HandBuiltMetadata</c>
/// exemplar. For the closed type set a document references it bakes, per type: the activation thunk
/// (<c>new T()</c>), the content property + collection flag, and the member table mirroring
/// <c>ReflectionXamlMetadata.BuildMember</c>'s ladder — a registered <c>UIProperty</c> (the
/// <c>&lt;Name&gt;Property</c> static field), a CLR property (setter/getter delegate), or an event. The
/// converter is emitted as a runtime <c>XamlConverters.For(typeof(...))</c> call, so it resolves
/// identically to the reflection provider (converter drift is impossible). No reflection, no
/// <c>System.Type</c> at generator time — only the consumer's <c>typeof</c>/field references.
/// </summary>
internal sealed class MetadataProviderEmitter
{
    private const string Ui = "https://cursorial.dev/ui";
    private const string Intrinsics = "https://cursorial.dev/xaml";
    private const string Frontend = "global::Cursorial.UI.Xaml";

    // The XAML2009 built-in (CLR basic) local names — resolved via the intrinsics (x:) namespace, keyed by the
    // System type's Name (System.Int32 → "Int32", etc., which equals the XAML2009 local name).
    private static readonly HashSet<string> BuiltInLocalNames =
    [
        "Object", "Boolean", "Byte", "SByte", "Char", "Decimal", "Single", "Double", "Int16", "Int32",
        "Int64", "UInt16", "UInt32", "UInt64", "String", "TimeSpan", "Uri",
    ];

    private static bool IsIntrinsicBuiltIn(INamedTypeSymbol s)
        => s.ContainingNamespace is { Name: "System", ContainingNamespace.IsGlobalNamespace: true }
           && BuiltInLocalNames.Contains(s.Name);

    private static string ArrayLiteral(IEnumerable<string> quotedItems)
    {
        var list = quotedItems.ToList();
        return list.Count == 0 ? "global::System.Array.Empty<string>()" : $"new[] {{ {string.Join(", ", list)} }}";
    }

    private readonly Compilation _compilation;

    public MetadataProviderEmitter(Compilation compilation) => _compilation = compilation;

    /// <summary>
    /// Emits the provider source for <paramref name="types"/> (resolved closed set), or null if empty. The
    /// provider is advertised via <c>[assembly: XamlMetadataProvider]</c> — pure PULL metadata: the loader's
    /// lazy default consults the ENTRY assembly's attribute (<c>XamlLoaderOptions.DefaultMetadataProvider</c>),
    /// so a library's attribute is inert and merely LOADING an assembly never repoints another host's default.
    /// Deliberately no <c>[ModuleInitializer]</c>: the old push-install hijacked any process that loaded the
    /// assembly (designer/test hosts), and parked provider mutation inside type-initialization machinery.
    /// </summary>
    public string? Emit(
        IReadOnlyList<INamedTypeSymbol> types,
        IReadOnlyList<(string Namespace, string Path, string Expr)>? statics = null)
    {
        if (types.Count == 0)
            return null;

        var staticList = (statics ?? System.Array.Empty<(string, string, string)>())
                         .OrderBy(s => s.Namespace, System.StringComparer.Ordinal)
                         .ThenBy(s => s.Path, System.StringComparer.Ordinal)
                         .ToList();

        // Deterministic order (display name) for stable output.
        var ordered = types
                      .Distinct(SymbolEqualityComparer.Default)
                      .Cast<INamedTypeSymbol>()
                      .OrderBy(t => t.ToDisplayString(), System.StringComparer.Ordinal)
                      .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Cursorial.UI.Xaml.Generator — generated metadata provider (WS-X4.5).");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("[assembly: " + Frontend + ".XamlMetadataProvider(typeof(Cursorial.UI.Xaml.Generated.__GeneratedXamlMetadata))]");
        sb.AppendLine();
        sb.AppendLine("namespace Cursorial.UI.Xaml.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    internal sealed class __GeneratedXamlMetadata : {Frontend}.IXamlTypeMetadataProvider, {Frontend}.IXamlQualifiedStaticResolver");
        sb.AppendLine("    {");
        sb.AppendLine("        public static readonly __GeneratedXamlMetadata Instance = new();");
        sb.AppendLine();

        EmitTryGetType(sb, ordered);
        EmitNamespaceTables(sb, ordered);
        EmitKnownMemberNames(sb, ordered);
        EmitTryResolveStatic(sb, staticList);

        foreach (var type in ordered)
            EmitType(sb, type);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private void EmitTryGetType(StringBuilder sb, List<INamedTypeSymbol> types)
    {
        var uiTypes = types.Where(t => !IsIntrinsicBuiltIn(t)).ToList();
        var builtins = types.Where(IsIntrinsicBuiltIn).ToList();

        sb.AppendLine($"        public {Frontend}.XamlTypeResolution TryGetType(string xmlNamespace, string localName)");
        sb.AppendLine("        {");

        EmitNamespaceSwitch(sb, Ui, uiTypes);
        // The XAML2009 built-in (CLR basic) types resolve via the intrinsics (x:) namespace — the canonical
        // <x:Int32>/<x:Array Type="x:String"> form, matching the reflection provider's XamlSchemaContext.
        if (builtins.Count > 0)
            EmitNamespaceSwitch(sb, Intrinsics, builtins);

        // clr-namespace:/using: URIs (an app's own views, sibling assemblies): the same types the
        // Roslyn resolver already admitted into the closed set, matched by their CLR namespace —
        // without this the generated provider knows less than the compile that produced it
        // (CUR2002 at runtime for a document the build had verified, the Cursorial.Samples bug).
        sb.AppendLine("            if (DecodeClrNamespace(xmlNamespace) is { } clrNamespace)");
        sb.AppendLine("                return TryGetClrNamespaceType(clrNamespace, localName);");
        sb.AppendLine();
        sb.AppendLine($"            return {Frontend}.XamlTypeResolution.NotFound();");
        sb.AppendLine("        }");
        sb.AppendLine();

        EmitClrNamespaceSwitch(sb, types);

        sb.AppendLine("        private static string? DecodeClrNamespace(string xmlNamespace)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (xmlNamespace.StartsWith(\"using:\", global::System.StringComparison.Ordinal))");
        sb.AppendLine("                return xmlNamespace.Substring(6);");
        sb.AppendLine("            if (!xmlNamespace.StartsWith(\"clr-namespace:\", global::System.StringComparison.Ordinal))");
        sb.AppendLine("                return null;");
        sb.AppendLine("            var body = xmlNamespace.Substring(14);");
        sb.AppendLine("            var semi = body.IndexOf(';');");
        sb.AppendLine("            return (semi < 0 ? body : body.Substring(0, semi)).Trim();");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private void EmitClrNamespaceSwitch(StringBuilder sb, List<INamedTypeSymbol> types)
    {
        sb.AppendLine($"        private static {Frontend}.XamlTypeResolution TryGetClrNamespaceType(string clrNamespace, string localName)");
        sb.AppendLine("        {");
        foreach (var group in types.GroupBy(t => t.ContainingNamespace.ToDisplayString(), System.StringComparer.Ordinal)
                                   .OrderBy(g => g.Key, System.StringComparer.Ordinal))
        {
            sb.AppendLine($"            if (string.Equals(clrNamespace, \"{group.Key}\", global::System.StringComparison.Ordinal))");
            sb.AppendLine("                return localName switch");
            sb.AppendLine("                {");
            foreach (var type in group.GroupBy(t => t.Name, System.StringComparer.Ordinal).Select(g => g.First()))
                sb.AppendLine($"                    \"{type.Name}\" => {Frontend}.XamlTypeResolution.Resolved({FieldName(type)}),");
            sb.AppendLine($"                    _ => {Frontend}.XamlTypeResolution.NotFound(),");
            sb.AppendLine("                };");
        }

        sb.AppendLine($"            return {Frontend}.XamlTypeResolution.NotFound();");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private void EmitNamespaceSwitch(StringBuilder sb, string xmlNamespace, List<INamedTypeSymbol> types)
    {
        sb.AppendLine($"            if (string.Equals(xmlNamespace, \"{xmlNamespace}\", global::System.StringComparison.Ordinal))");
        sb.AppendLine("                return localName switch");
        sb.AppendLine("                {");
        foreach (var type in types)
            sb.AppendLine($"                    \"{type.Name}\" => {Frontend}.XamlTypeResolution.Resolved({FieldName(type)}),");
        sb.AppendLine($"                    _ => {Frontend}.XamlTypeResolution.NotFound(),");
        sb.AppendLine("                };");
    }

    private void EmitNamespaceTables(StringBuilder sb, List<INamedTypeSymbol> types)
    {
        var uiTypes = types.Where(t => !IsIntrinsicBuiltIn(t)).ToList();
        var builtins = types.Where(IsIntrinsicBuiltIn).ToList();

        var uiNamespaces = uiTypes.Select(t => t.ContainingNamespace.ToDisplayString())
                                  .Distinct(System.StringComparer.Ordinal).OrderBy(n => n, System.StringComparer.Ordinal)
                                  .Select(n => $"\"{n}\"");
        var uiNames = uiTypes.Select(t => t.Name).Distinct(System.StringComparer.Ordinal)
                             .OrderBy(n => n, System.StringComparer.Ordinal).Select(n => $"\"{n}\"");
        var builtinNames = builtins.Select(t => t.Name).Distinct(System.StringComparer.Ordinal)
                                   .OrderBy(n => n, System.StringComparer.Ordinal).Select(n => $"\"{n}\"");

        sb.AppendLine("        public string[] GetClrNamespaces(string xmlNamespace) =>");
        sb.AppendLine(
            $"            string.Equals(xmlNamespace, \"{Ui}\", global::System.StringComparison.Ordinal) ? {ArrayLiteral(uiNamespaces)}");
        sb.AppendLine($"            : global::System.Array.Empty<string>();");
        sb.AppendLine();

        sb.AppendLine("        public string[] GetKnownTypeNames(string xmlNamespace) =>");
        sb.AppendLine(
            $"            string.Equals(xmlNamespace, \"{Ui}\", global::System.StringComparison.Ordinal) ? {ArrayLiteral(uiNames)}");
        sb.AppendLine(
            $"            : string.Equals(xmlNamespace, \"{Intrinsics}\", global::System.StringComparison.Ordinal) ? {ArrayLiteral(builtinNames)}");
        sb.AppendLine($"            : global::System.Array.Empty<string>();");
        sb.AppendLine();
    }

    private void EmitKnownMemberNames(StringBuilder sb, List<INamedTypeSymbol> types)
    {
        sb.AppendLine("        public string[] GetKnownMemberNames(global::Cursorial.UI.Xaml.IXamlType xamlType)");
        sb.AppendLine("        {");
        sb.AppendLine("            var clrType = xamlType.UnderlyingSystemType;");

        foreach (var type in types)
        {
            var names = SymbolXamlModel.EnumerateMembers(type).Select(m => m.Name).Distinct(System.StringComparer.Ordinal).OrderBy(n => n, System.StringComparer.Ordinal).ToList();
            // A type with no XAML-visible members (e.g. a built-in primitive like System.Int32 used as an
            // <x:Int32> element) emits Array.Empty — `new[] { }` is a CS0826 (no best type for an empty array).
            var ret = names.Count == 0 ? "global::System.Array.Empty<string>()" : $"new[] {{ {string.Join(", ", names.Select(n => $"\"{n}\""))} }}";
            sb.AppendLine($"            if (clrType == typeof({Global(type)})) return {ret};");
        }

        sb.AppendLine("            return global::System.Array.Empty<string>();");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    // WS-X4.5 / P1B — the AOT-clean {x:Static} seam (IXamlQualifiedStaticResolver): a baked switch over the
    // document set's referenced static members → `global::FullType.Member`, keyed by the (xmlns, prefix-free
    // path) pair the loader binds (P1C). The consumer's compile resolves the refs (no System.Type at generator
    // time, identical to the converter strategy). An x:Static the generator can't resolve isn't baked (the
    // runtime then reports member-not-found, matching the reflection provider — no drift). The raw-path form
    // scopes to the default UI uri, mirroring ReflectionXamlMetadata.
    private void EmitTryResolveStatic(StringBuilder sb, IReadOnlyList<(string Namespace, string Path, string Expr)> statics)
    {
        sb.AppendLine("        public bool TryResolveStatic(string memberPath, out object? value)");
        sb.AppendLine($"            => TryResolveStatic(\"{Ui}\", memberPath, out value);");
        sb.AppendLine();
        sb.AppendLine("        public bool TryResolveStatic(string xmlNamespace, string memberPath, out object? value)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (xmlNamespace, memberPath)");
        sb.AppendLine("            {");

        foreach (var (ns, path, expr) in statics)
            sb.AppendLine($"                case (\"{Escape(ns)}\", \"{Escape(path)}\"): value = {expr}; return true;");

        sb.AppendLine("                default: value = null; return false;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private void EmitType(StringBuilder sb, INamedTypeSymbol type)
    {
        var field = FieldName(type);
        var members = SymbolXamlModel.EnumerateMembers(type).ToList();
        var contentProperty = SymbolXamlModel.ResolveContentProperty(type);
        var isDictionary = SymbolXamlModel.IsResourceDictionary(type);
        var contentIsCollection = contentProperty is not null && SymbolXamlModel.ContentIsCollection(type, contentProperty);
        var isCollection = contentIsCollection || isDictionary;
        var requiresInit = SymbolXamlModel.RequiresInitialize(type);

        sb.AppendLine($"        private static readonly {Frontend}.XamlType {field} = Build_{field}();");
        sb.AppendLine($"        private static {Frontend}.XamlType Build_{field}()");
        sb.AppendLine("        {");

        sb.AppendLine(
            $"            var members = new global::System.Collections.Generic.Dictionary<string, {Frontend}.XamlMember>(global::System.StringComparer.Ordinal)");

        sb.AppendLine("            {");

        foreach (var member in members)
            sb.AppendLine("                " + EmitMember(type, member) + ",");

        // Style.TargetType is SYNTHETIC (a Style matches via Selector; TargetType is the parse-time
        // Setter-resolution hint, matrix X139) — special-cased in the reflection provider AND the
        // Roslyn resolver; the emitted provider must carry the same rung or a runtime-loaded
        // dictionary that authored TargetType dies with CUR2102 under the generated default.
        if (type.ToDisplayString() == "Cursorial.UI.Style")
            sb.AppendLine($"                [\"TargetType\"] = new {Frontend}.XamlMember(\"TargetType\", typeof(global::System.Type)),");

        sb.AppendLine("            };");
        // A ResourceDictionary is filled via Add(key, value) with object keys (matrix XD10/C-8).
        var addDictionaryItem = isDictionary
            ? $"static (d, k, v) => (({Global(type)})d).Add(k, v)"
            : "null";
        var dictionaryKeyType = isDictionary ? "typeof(object)" : "null";

        sb.AppendLine($"            return new {Frontend}.XamlType(");
        sb.AppendLine($"                clrType: typeof({Global(type)}),");
        sb.AppendLine($"                activate: {(SymbolXamlModel.CanActivate(type) ? $"static () => new {Global(type)}()" : "null")},");
        sb.AppendLine($"                contentProperty: {(contentProperty is null ? "null" : $"\"{contentProperty}\"")},");
        sb.AppendLine($"                isCollection: {(isCollection ? "true" : "false")},");
        sb.AppendLine($"                addDictionaryItem: {addDictionaryItem},");
        sb.AppendLine($"                dictionaryKeyType: {dictionaryKeyType},");
        sb.AppendLine($"                requiresInitialize: {(requiresInit ? "true" : "false")},");
        sb.AppendLine("                memberResolver: name => members.TryGetValue(name, out var m) ? m : null);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private string EmitMember(INamedTypeSymbol owner, SymbolXamlModel.MemberModel member)
    {
        var valueTypeOf = $"typeof({Global(member.ValueType)})";

        // A member (or its value type) carrying a [TypeConverter]/[ValueSerializer] resolves through the runtime
        // ForMember — the SAME method the reflection provider uses, so the WPF precedence, the converter's
        // accessibility, the string-name ctor form, and the BCL-attribute exclusion all resolve identically (zero
        // drift; no `new T()` baking that could break on a non-public type/ctor). A member with NO converter
        // attribute bakes the pure, reflection-free For(typeof(T)) ladder — the AOT-clean common path.
        var converter = member.UsesAttributeConverter
            ? $"{Frontend}.XamlConverters.ForMember(typeof({Global(owner)}).GetProperty(\"{member.Name}\", global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Instance), {valueTypeOf})"
            : $"{Frontend}.XamlConverters.For({valueTypeOf})";

        // An ITemplateContent-typed member is deferred content (its children are a deferred slice with their
        // own template name scope) — mirror ReflectionXamlMetadata's IsDeferredContent stamp.
        var deferred = SymbolXamlModel.IsDeferredContent(member.ValueType) ? " { IsDeferredContent = true }" : string.Empty;

        if (member.IsEvent)
            return $"[\"{member.Name}\"] = new {Frontend}.XamlMember(\"{member.Name}\", {valueTypeOf}, isEvent: true){deferred}";

        if (member.RegisteredFieldOwner is not null)
        {
            // Registered UIProperty: property: <DeclaringType>.<Name>Property. An attached property (Grid.Row)
            // additionally carries isAttachable: true so the loader assigns it through the attached registration.
            var prop = $"{Global(member.RegisteredFieldOwner)}.{member.Name}Property";
            var attachable = member.IsAttached ? ", isAttachable: true" : string.Empty;
            return $"[\"{member.Name}\"] = new {Frontend}.XamlMember(\"{member.Name}\", {valueTypeOf}, property: {prop}, converter: {converter}{attachable}){deferred}";
        }

        // CLR property: setClr / get delegates. An init-only setter can't be a compiled `t.Prop = v` (CS8852),
        // so it's set reflectively — same as ReflectionXamlMetadata, and correct for a boxed struct (Pen) too.
        // (A future AOT-clean upgrade is an [UnsafeAccessor] set_<Name> thunk; reflection keeps it simple now.)
        var setClr = member.CanWrite
                         ? member.IsInitOnly
                               ? $"setClr: (t, v) => typeof({Global(owner)}).GetProperty(\"{member.Name}\")!.SetValue(t, v)"
                               : $"setClr: (t, v) => (({Global(owner)})t).{member.Name} = ({Global(member.ValueType)})v!"
                         : null;

        var get = member.CanRead ? $"get: t => (({Global(owner)})t).{member.Name}" : null;
        var parts = new List<string> { $"\"{member.Name}\"", valueTypeOf };
        if (setClr is not null) parts.Add(setClr);
        if (get is not null) parts.Add(get);
        parts.Add($"converter: {converter}");
        return $"[\"{member.Name}\"] = new {Frontend}.XamlMember({string.Join(", ", parts)}){deferred}";
    }

    // ── codegen helpers ───────────────────────────────────────────────────────────────────────────

    private static string FieldName(INamedTypeSymbol type) => type.Name;

    private static string Global(ITypeSymbol type)
        => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string Escape(string text) => text.Replace("\\", "\\\\").Replace("\"", "\\\"");
}