using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;

namespace Cursorial.UI.Xaml.Generator;

/// <summary>
/// Emits the generated <c>IXamlTypeMetadataProvider</c> (design doc §4.9 / WS-X4.5) — the trim/AOT-clean
/// analog of <c>ReflectionXamlMetadata</c>, shaped exactly like the hand-written <c>HandBuiltMetadata</c>
/// exemplar. For the closed type set a document references it bakes, per type: the activation thunk
/// (<c>new T()</c>), the content property + collection flag, and the member table mirroring
/// <c>ReflectionXamlMetadata.BuildMember</c>'s ladder — a registered <c>UIProperty</c> (the
/// <c>&lt;Name&gt;Property</c> static field), a CLR property (setter/getter delegate), or an event. The
/// converter is emitted as a runtime <c>XamlConverters.For(typeof(...))</c> call, so it resolves
/// identically to the reflection provider (converter drift is impossible). No reflection, no
/// <c>System.Type</c> at generator time — only the consumer's <c>typeof</c>/field references.
/// </summary>
internal sealed class MetadataProviderEmitter
{
    private const string Ui = "https://cursorial.dev/ui";
    private const string Frontend = "global::Cursorial.UI.Xaml";

    private readonly Compilation _compilation;

    public MetadataProviderEmitter(Compilation compilation) => _compilation = compilation;

    /// <summary>Emits the provider source for <paramref name="types"/> (resolved closed set), or null if empty.</summary>
    public string? Emit(IReadOnlyList<INamedTypeSymbol> types)
    {
        if (types.Count == 0)
            return null;

        // Deterministic order (display name) for stable output.
        var ordered = types
                      .Distinct(SymbolEqualityComparer.Default)
                      .Cast<INamedTypeSymbol>()
                      .OrderBy(t => t.ToDisplayString(), System.StringComparer.Ordinal)
                      .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Cursorial.UI.Xaml.Generator — generated metadata provider (WS-X4.5).");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("[assembly: " + Frontend + ".XamlMetadataProvider(typeof(Cursorial.UI.Xaml.Generated.__GeneratedXamlMetadata))]");
        sb.AppendLine();
        sb.AppendLine("namespace Cursorial.UI.Xaml.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    internal sealed class __GeneratedXamlMetadata : {Frontend}.IXamlTypeMetadataProvider");
        sb.AppendLine("    {");
        sb.AppendLine("        public static readonly __GeneratedXamlMetadata Instance = new();");
        sb.AppendLine();

        EmitTryGetType(sb, ordered);
        EmitNamespaceTables(sb, ordered);
        EmitKnownMemberNames(sb, ordered);

        foreach (var type in ordered)
            EmitType(sb, type);

        sb.AppendLine("    }");
        sb.AppendLine();
        // A module initializer installs the generated provider as the loader's process default — AOT-clean
        // (no reflection), so the consuming assembly uses it automatically without any explicit opt-in.
        sb.AppendLine("    internal static class __GeneratedXamlMetadataModuleInit");
        sb.AppendLine("    {");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void Initialize()");
        sb.AppendLine($"            => global::Cursorial.UI.Xaml.XamlLoaderOptions.DefaultMetadataProvider = __GeneratedXamlMetadata.Instance;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private void EmitTryGetType(StringBuilder sb, List<INamedTypeSymbol> types)
    {
        sb.AppendLine($"        public {Frontend}.XamlTypeResolution TryGetType(string xmlNamespace, string localName)");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (!string.Equals(xmlNamespace, \"{Ui}\", global::System.StringComparison.Ordinal))");
        sb.AppendLine($"                return {Frontend}.XamlTypeResolution.NotFound();");
        sb.AppendLine("            return localName switch");
        sb.AppendLine("            {");

        foreach (var type in types)
            sb.AppendLine($"                \"{type.Name}\" => {Frontend}.XamlTypeResolution.Resolved({FieldName(type)}),");

        sb.AppendLine($"                _ => {Frontend}.XamlTypeResolution.NotFound(),");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private void EmitNamespaceTables(StringBuilder sb, List<INamedTypeSymbol> types)
    {
        var namespaces = types.Select(t => t.ContainingNamespace.ToDisplayString())
                              .Distinct(System.StringComparer.Ordinal)
                              .OrderBy(n => n, System.StringComparer.Ordinal);

        var typeNames = types.Select(t => t.Name).Distinct(System.StringComparer.Ordinal).OrderBy(n => n, System.StringComparer.Ordinal);

        sb.AppendLine("        public string[] GetClrNamespaces(string xmlNamespace) =>");

        sb.AppendLine(
            $"            string.Equals(xmlNamespace, \"{Ui}\", global::System.StringComparison.Ordinal) ? new[] {{ {string.Join(", ", namespaces.Select(n => $"\"{n}\""))} }} : global::System.Array.Empty<string>();");

        sb.AppendLine();
        sb.AppendLine("        public string[] GetKnownTypeNames(string xmlNamespace) =>");

        sb.AppendLine(
            $"            string.Equals(xmlNamespace, \"{Ui}\", global::System.StringComparison.Ordinal) ? new[] {{ {string.Join(", ", typeNames.Select(n => $"\"{n}\""))} }} : global::System.Array.Empty<string>();");

        sb.AppendLine();
    }

    private void EmitKnownMemberNames(StringBuilder sb, List<INamedTypeSymbol> types)
    {
        sb.AppendLine("        public string[] GetKnownMemberNames(global::Cursorial.UI.Xaml.IXamlType xamlType)");
        sb.AppendLine("        {");
        sb.AppendLine("            var clrType = xamlType.UnderlyingSystemType;");

        foreach (var type in types)
        {
            var names = SymbolXamlModel.EnumerateMembers(type).Select(m => m.Name).Distinct(System.StringComparer.Ordinal).OrderBy(n => n, System.StringComparer.Ordinal);
            sb.AppendLine($"            if (clrType == typeof({Global(type)})) return new[] {{ {string.Join(", ", names.Select(n => $"\"{n}\""))} }};");
        }

        sb.AppendLine("            return global::System.Array.Empty<string>();");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private void EmitType(StringBuilder sb, INamedTypeSymbol type)
    {
        var field = FieldName(type);
        var members = SymbolXamlModel.EnumerateMembers(type).ToList();
        var contentProperty = SymbolXamlModel.ResolveContentProperty(type);
        var isDictionary = SymbolXamlModel.IsResourceDictionary(type);
        var contentIsCollection = contentProperty is not null && SymbolXamlModel.ContentIsCollection(type, contentProperty);
        var isCollection = contentIsCollection || isDictionary;
        var requiresInit = SymbolXamlModel.RequiresInitialize(type);

        sb.AppendLine($"        private static readonly {Frontend}.XamlType {field} = Build_{field}();");
        sb.AppendLine($"        private static {Frontend}.XamlType Build_{field}()");
        sb.AppendLine("        {");

        sb.AppendLine(
            $"            var members = new global::System.Collections.Generic.Dictionary<string, {Frontend}.XamlMember>(global::System.StringComparer.Ordinal)");

        sb.AppendLine("            {");

        foreach (var member in members)
            sb.AppendLine("                " + EmitMember(type, member) + ",");

        sb.AppendLine("            };");
        // A ResourceDictionary is filled via Add(key, value) with object keys (matrix XD10/C-8).
        var addDictionaryItem = isDictionary
            ? $"static (d, k, v) => (({Global(type)})d).Add(k, v)"
            : "null";
        var dictionaryKeyType = isDictionary ? "typeof(object)" : "null";

        sb.AppendLine($"            return new {Frontend}.XamlType(");
        sb.AppendLine($"                clrType: typeof({Global(type)}),");
        sb.AppendLine($"                activate: {(SymbolXamlModel.CanActivate(type) ? $"static () => new {Global(type)}()" : "null")},");
        sb.AppendLine($"                contentProperty: {(contentProperty is null ? "null" : $"\"{contentProperty}\"")},");
        sb.AppendLine($"                isCollection: {(isCollection ? "true" : "false")},");
        sb.AppendLine($"                addDictionaryItem: {addDictionaryItem},");
        sb.AppendLine($"                dictionaryKeyType: {dictionaryKeyType},");
        sb.AppendLine($"                requiresInitialize: {(requiresInit ? "true" : "false")},");
        sb.AppendLine("                memberResolver: name => members.TryGetValue(name, out var m) ? m : null);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private string EmitMember(INamedTypeSymbol owner, SymbolXamlModel.MemberModel member)
    {
        var valueTypeOf = $"typeof({Global(member.ValueType)})";
        var converter = $"{Frontend}.XamlConverters.For({valueTypeOf})";

        // An ITemplateContent-typed member is deferred content (its children are a deferred slice with their
        // own template name scope) — mirror ReflectionXamlMetadata's IsDeferredContent stamp.
        var deferred = SymbolXamlModel.IsDeferredContent(member.ValueType) ? " { IsDeferredContent = true }" : string.Empty;

        if (member.IsEvent)
            return $"[\"{member.Name}\"] = new {Frontend}.XamlMember(\"{member.Name}\", {valueTypeOf}, isEvent: true){deferred}";

        if (member.RegisteredFieldOwner is not null)
        {
            // Registered UIProperty: property: <DeclaringType>.<Name>Property. An attached property (Grid.Row)
            // additionally carries isAttachable: true so the loader assigns it through the attached registration.
            var prop = $"{Global(member.RegisteredFieldOwner)}.{member.Name}Property";
            var attachable = member.IsAttached ? ", isAttachable: true" : string.Empty;
            return $"[\"{member.Name}\"] = new {Frontend}.XamlMember(\"{member.Name}\", {valueTypeOf}, property: {prop}, converter: {converter}{attachable}){deferred}";
        }

        // CLR property: setClr / get delegates.
        var setClr = member.CanWrite
                         ? $"setClr: (t, v) => (({Global(owner)})t).{member.Name} = ({Global(member.ValueType)})v!"
                         : null;

        var get = member.CanRead ? $"get: t => (({Global(owner)})t).{member.Name}" : null;
        var parts = new List<string> { $"\"{member.Name}\"", valueTypeOf };
        if (setClr is not null) parts.Add(setClr);
        if (get is not null) parts.Add(get);
        parts.Add($"converter: {converter}");
        return $"[\"{member.Name}\"] = new {Frontend}.XamlMember({string.Join(", ", parts)}){deferred}";
    }

    // ── codegen helpers ───────────────────────────────────────────────────────────────────────────

    private static string FieldName(INamedTypeSymbol type) => type.Name;

    private static string Global(ITypeSymbol type)
        => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
}