using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Cursorial.UI.Xaml.Generator;

/// <summary>
/// The Fork C X4 incremental XAML generator (design doc §4.9, P10). Skeleton (WS-X4.1): it discovers
/// the project's <c>CursorialXaml</c> items (surfaced as <see cref="AdditionalText"/> with a
/// <c>SourceItemType=CursorialXaml</c> metadata flag by the package targets) and, for now, emits a
/// per-file marker so the analyzer-load + MSBuild-item plumbing is verifiable before the codegen
/// passes (validation diagnostics, <c>x:Name</c> fields + <c>InitializeComponent</c>, the generated
/// <c>IXamlTypeMetadataProvider</c>) land in WS-X4.4–X4.6.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class XamlSourceGenerator : IIncrementalGenerator
{
    private const string SourceItemTypeKey = "build_metadata.AdditionalFiles.SourceItemType";
    private const string CursorialXamlItemType = "CursorialXaml";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Each CursorialXaml file → (hint name, text). Filtered to our item type so a stray .xaml added
        // as a plain AdditionalFiles isn't picked up.
        var xamlFiles = context.AdditionalTextsProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Where(static pair =>
            {
                var (file, options) = pair;
                if (!file.Path.EndsWith(".xaml", System.StringComparison.OrdinalIgnoreCase))
                    return false;
                return options.GetOptions(file).TryGetValue(SourceItemTypeKey, out var itemType)
                    && string.Equals(itemType, CursorialXamlItemType, System.StringComparison.OrdinalIgnoreCase);
            })
            .Select(static (pair, ct) => pair.Left.GetText(ct)?.ToString() is { } text
                ? new XamlInput(System.IO.Path.GetFileNameWithoutExtension(pair.Left.Path), text)
                : new XamlInput(System.IO.Path.GetFileNameWithoutExtension(pair.Left.Path), string.Empty));

        context.RegisterSourceOutput(xamlFiles, static (spc, input) =>
        {
            // WS-X4.1 marker output — proves the file reached the generator with the right item metadata.
            var hint = SanitizeHint(input.Name) + ".g.cs";
            var src =
                "// <auto-generated/> Cursorial.UI.Xaml.Generator (WS-X4.1 skeleton)\n" +
                $"// source: {input.Name}.xaml ({input.Text.Length} chars)\n";
            spc.AddSource(hint, SourceText.From(src, Encoding.UTF8));
        });
    }

    private static string SanitizeHint(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        return sb.Length == 0 ? "Xaml" : sb.ToString();
    }

    private readonly record struct XamlInput(string Name, string Text);
}
