using System.Collections.Generic;
using System.Text;

using Cursorial.UI.Xaml; // source-linked frontend: XamlFrontend, XamlDocument, XamlDiagnostic, XamlParseOptions

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Cursorial.UI.Xaml.Generator;

/// <summary>
/// The Fork C X4 incremental XAML generator (design doc §4.9, P10). It discovers the project's
/// <c>CursorialXaml</c> items (surfaced as <see cref="AdditionalText"/> flagged
/// <c>SourceItemType=CursorialXaml</c> by the package targets), runs the SAME netstandard2.0
/// <c>XamlFrontend.Parse</c> the loader runs (source-linked), and emits:
/// <list type="bullet">
/// <item>WS-X4.4 — the parser's <see cref="XamlDiagnostic"/>s as Roslyn build diagnostics at the
/// <c>.xaml</c> location (syntax band <c>CUR1xxx</c> today; the semantic band joins once the
/// build-time <c>RoslynXamlMetadata</c> provider lands at WS-X4.3).</item>
/// <item>WS-X4.5/X4.6 (forthcoming) — the generated metadata provider and the typed <c>x:Name</c>
/// fields + <c>InitializeComponent</c>.</item>
/// </list>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class XamlSourceGenerator : IIncrementalGenerator
{
    private const string SourceItemTypeKey = "build_metadata.AdditionalFiles.SourceItemType";
    private const string CursorialXamlItemType = "CursorialXaml";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Each CursorialXaml file → an equatable (path, text) input (filtered to our item type so a stray
        // .xaml added as a plain AdditionalFiles isn't picked up). Equatable strings drive incrementality.
        var xamlFiles = context.AdditionalTextsProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Where(static pair =>
            {
                var (file, options) = pair;
                if (!file.Path.EndsWith(".xaml", System.StringComparison.OrdinalIgnoreCase))
                    return false;
                return options.GetOptions(file).TryGetValue(SourceItemTypeKey, out var itemType)
                    && string.Equals(itemType, CursorialXamlItemType, System.StringComparison.OrdinalIgnoreCase);
            })
            .Select(static (pair, ct) => new XamlInput(
                pair.Left.Path,
                pair.Left.GetText(ct)?.ToString() ?? string.Empty));

        context.RegisterSourceOutput(xamlFiles, static (spc, input) => Emit(spc, input));
    }

    private static void Emit(SourceProductionContext spc, XamlInput input)
    {
        // Run the same parser the loader runs (syntax mode: no metadata provider yet — WS-X4.3 adds the
        // symbol-backed provider for the semantic band). CollectAll so a malformed document yields every
        // diagnostic rather than throwing on the first.
        XamlDocument document;
        try
        {
            document = XamlFrontend.Parse(
                input.Text,
                new XamlParseOptions { DiagnosticMode = XamlDiagnosticMode.CollectAll },
                source: null);
        }
        catch (System.Exception ex)
        {
            // The parser should not throw under CollectAll; treat any escape as an internal-error diagnostic
            // rather than crashing the compiler.
            spc.ReportDiagnostic(Diagnostic.Create(InternalError, Location.None, input.Path, ex.Message));
            return;
        }

        foreach (var diagnostic in document.Diagnostics)
        {
            // Syntax mode: only the CUR1xxx parse band is sound without type resolution. The CUR2xxx
            // (resolution) / CUR3xxx (instantiation) bands would false-positive on every element while
            // the metadata provider is null — they join once WS-X4.3's RoslynXamlMetadata lands.
            if (!diagnostic.Code.StartsWith("CUR1", System.StringComparison.Ordinal))
                continue;
            spc.ReportDiagnostic(ToRoslyn(diagnostic, input));
        }

        // WS-X4.1 marker (retained until the codegen passes replace it) — proves the file reached the generator.
        var hint = SanitizeHint(System.IO.Path.GetFileNameWithoutExtension(input.Path)) + ".g.cs";
        var rootClass = document.RootClassName is { Length: > 0 } rc ? rc : "(none)";
        var src =
            "// <auto-generated/> Cursorial.UI.Xaml.Generator\n" +
            $"// source: {input.Path}\n" +
            $"// x:Class: {rootClass}; diagnostics: {document.Diagnostics.Count}\n";
        spc.AddSource(hint, SourceText.From(src, Encoding.UTF8));
    }

    private static Diagnostic ToRoslyn(XamlDiagnostic diagnostic, XamlInput input)
    {
        var severity = diagnostic.Severity switch
        {
            XamlDiagnosticSeverity.Error => DiagnosticSeverity.Error,
            XamlDiagnosticSeverity.Warning => DiagnosticSeverity.Warning,
            _ => DiagnosticSeverity.Info,
        };

        // One descriptor per CUR code (cached) — the message is the format argument.
        var descriptor = DescriptorFor(diagnostic.Code, severity);
        return Diagnostic.Create(descriptor, LocationFor(input, diagnostic.Line, diagnostic.Column), diagnostic.Message);
    }

    private static readonly Dictionary<string, DiagnosticDescriptor> DescriptorCache = new();
    private static readonly object DescriptorLock = new();

    private static DiagnosticDescriptor DescriptorFor(string code, DiagnosticSeverity severity)
    {
        lock (DescriptorLock)
        {
            var key = code + (char)severity;
            if (DescriptorCache.TryGetValue(key, out var cached))
                return cached;

            var descriptor = new DiagnosticDescriptor(
                id: code,
                title: "XAML " + code,
                messageFormat: "{0}",
                category: "Cursorial.Xaml",
                defaultSeverity: severity,
                isEnabledByDefault: true);
            DescriptorCache[key] = descriptor;
            return descriptor;
        }
    }

    private static readonly DiagnosticDescriptor InternalError = new(
        id: "CURG0001",
        title: "XAML generator internal error",
        messageFormat: "The XAML generator failed on '{0}': {1}",
        category: "Cursorial.Xaml",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    // Builds a Roslyn Location on the .xaml file from the frontend's 1-based line/column.
    private static Location LocationFor(XamlInput input, int line, int column)
    {
        if (line <= 0 || column <= 0)
            return Location.None;

        var text = SourceText.From(input.Text);
        var zeroLine = line - 1;
        if (zeroLine >= text.Lines.Count)
            return Location.None;

        var textLine = text.Lines[zeroLine];
        var start = textLine.Start + System.Math.Min(column - 1, textLine.End - textLine.Start);
        var position = new LinePosition(zeroLine, column - 1);
        return Location.Create(input.Path, new TextSpan(start, 0), new LinePositionSpan(position, position));
    }

    private static string SanitizeHint(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        return sb.Length == 0 ? "Xaml" : sb.ToString();
    }

    private readonly record struct XamlInput(string Path, string Text);
}
